### ISSUE TITLE
pip-compile should have an --exclude option for blacklisting packages from output

### ISSUE THREAD

**Issue by ssbarnea** [jazzband/pip-tools#1431] opened 2021-06-22 16:01 UTC
There are are use cases where users may want to exclude (blacklist) a wider range of packages from being added to the output file, not only `setuptools`.

I am aware of at least one [big project that is building constraint files with all dependencies while excluding a special list of packages from being included in the output](https://opendev.org/openstack/requirements/src/branch/master/blacklist.txt).

I would like to propose adding an `-e, --exclude filename` option which would ensure that the package names from that file are not included in the output.

Does this makes sense or not?

**Comment by cjerdonek** [comment] 2021-08-12 20:15
Is this a duplicate of #333?

**Closed** 2021-09-12 13:53 UTC
Labels: feature request
