### ISSUE TITLE
Unable to install alembic

### ISSUE THREAD

**Issue by parasvanjani** [jazzband/pip-tools#1104] opened 2020-04-04 06:20 UTC
Below is the error I get:

> pip._internal.exceptions.InstallationError: Command "d:\schonfeld\panda-service\venv\scripts\python.exe d:\schonfeld\panda-service\venv\lib\site-packages\pip-19.0.3-py3.6.egg
> \pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\Vanjani\AppData\Local\Temp\tmp7fm47rxc" failed with error code 1 in C:\Users\Vanjani\AppData\Local\Temp\tmpjkc7fa14build\alembic
> 

#### Environment Versions

1. OS Type - Windows 10
1. Python version: `$ python -V` Python 3.6.8
1. pip version:  `$ pip --version` pip 19.0.3 
1. pip-tools version: `$ pip-compile --version` pip-compile, version 4.5.1

#### Steps to replicate

1. Requirements file only has `alembic`
2. here is the output for pip-compile -v
`$ pip-compile.exe -v development/requirements-test.in
Using indexes:
  https://pypi.org/simple

                          ROUND 1                           
Current constraints:
  alembic (from -r development/requirements-test.in (line 1))

Finding the best candidates:
  found candidate alembic==1.4.2 (constraint was <any>)

Finding secondary dependencies:
  alembic==1.4.2 not in cache, need to check index
Traceback (most recent call last):
  File "D:\softwares\install\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\softwares\install\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\test\venv\Scripts\pip-compile.exe\__main__.py", line 9, in <module>
  File "d:\test\venv\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\test\venv\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\test\venv\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\test\venv\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\test\venv\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\test\venv\lib\site-packages\piptools\scripts\compile.py", line 391, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "d:\test\venv\lib\site-packages\piptools\resolver.py", line 164, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "d:\test\venv\lib\site-packages\piptools\resolver.py", line 259, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "d:\test\venv\lib\site-packages\piptools\resolver.py", line 365, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "d:\test\venv\lib\site-packages\piptools\repositories\local.py", line 70, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "d:\test\venv\lib\site-packages\piptools\repositories\pypi.py", line 295, in get_dependencies
    download_dir, ireq, wheel_cache
  File "d:\test\venv\lib\site-packages\piptools\repositories\pypi.py", line 252, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\operations\prepare.py", line 349, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\operations\prepare.py", line 158, in prep_for_dist
    self.req.prepare_metadata()
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 528, in prepare_metadata
    self.prepare_pep517_metadata()
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 573, in prepare_pep517_metadata
    metadata_dir
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_vendor\pep517\wrappers.py", line 86, in prepare_metadata_for_build_wheel
    'config_settings': config_settings,
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_vendor\pep517\wrappers.py", line 155, in _call_hook
    extra_environ={'PEP517_BUILD_BACKEND': build_backend}
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\req\req_install.py", line 511, in runner
    spinner=spinner
  File "d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg\pip\_internal\utils\misc.py", line 761, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "d:\test\venv\scripts\python.exe d:\test\venv\lib\site-packages\pip-19.0.3-py3.6.egg
\pip\_vendor\pep517\_in_process.py prepare_metadata_for_build_wheel C:\Users\Vanjani\AppData\Local\Temp\tmpis20_ef5" failed with error code 1 in C:\Users\Vanjani\AppData\Loca
l\Temp\tmp_hjtmb25build\alembic

`
#### Expected result
Should be able to generate requirements.txt

**Comment by atugushev** [comment] 2020-04-04 13:57
Looks like it's a dupe of #1103. Feel free to reopen it if you sill have any issues.

**Closed by atugushev** 2020-04-04 13:57 UTC
