### ISSUE TITLE
Would it be possible to prevent `pip-compile` to replace `.` into `-`?

### ISSUE THREAD

**Issue by avatar-lavventura** [jazzband/pip-tools#1595] opened 2022-03-07 14:21 UTC
#### Environment Versions

1. OS Type Ubuntu
1. Python 3.8.10
1. pip 22.0.4 from /home/alper/venv/lib/python3.8/site-packages/pip (python 3.8)
1. pip-compile, version 6.5.1
-------------
pip-compile changes all `.`  into `-` which affects the correct pip installations, causes errors as follows:

```
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zope-traversing==4.4.1' distribution was not found and is required by ebloc-broker
An exception of type DistributionNotFound occurred. Arguments:
(Requirement.parse('zope-traversing==4.4.1'), {'ebloc-broker'})
```

due to:  `zope-traversing` replaced into `zope.traversing`

Example:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/18537398/157051941-510e5583-4510-4334-bef6-9a5a8625a5da.png">

For example it changes `zope.traversing` into `zope-traversing` , which is in correct.

Would it be possible to prevent `pip-compile` to replace `.`?

**Comment by AndydeCleyre** [comment] 2022-03-07 14:34
Have you seen #1576?

**Comment by AndydeCleyre** [comment] 2022-03-07 14:36
Thanks for reporting! Can you provide reproducible steps for that error message?

**Comment by avatar-lavventura** [comment] 2022-03-07 14:44
They way I have installed python and activated `venv` other than that I have latest `pip-tools` and I just run `pip-compile`: 

```python
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa -y
sudo apt-get update
sudo apt install python-dev -y
sudo apt install python2 -y
sudo apt install python-psutil -y
sudo apt install python3-dev -y
sudo apt install python3-pip -y
sudo apt install python3-venv -y
sudo apt install python3-virtualenv -y
sudo apt install python3.7 -y
sudo apt install python3.8-dev -y
sudo apt install python3.8-venv -y

VENV=$HOME/venv
python3.8 -m venv $VENV
source $VENV/bin/activate && $VENV/bin/python3.8 -m pip install --upgrade pip
sudo apt-get install -y libssl-dev zlib1g-dev gcc g++ make libgirepository1.0-dev
python3 -m pip install --no-use-pep517 cm-rgb
$VENV/bin/python3 -m pip install wheel -U
$VENV/bin/python3 -m pip install pip-tools -U
```

**Comment by AndydeCleyre** [comment] 2022-03-07 14:55
Are you saying that running pip-compile directly raises that DistributionNotFound exception? If not, can you provide steps to reproduce that?

**Comment by AndydeCleyre** [comment] 2022-03-07 17:07
OK I took your example setup file, replaced `long_description` with a string to make it valid, added a `requirements.in` with `zope.traversal` and generated a corresponding `.txt`, ran `pip install -e .` and everything installed successfully.

Now you are getting an error when you, what, use the setuptools-generated console script? Or when you use the code generally? If it's just the setuptools-generated console script that fails, I think that's a setuptools bug, as I wrote about in #1576 -- have you read that one yet?

If it *is* just the generated script file that's the problem, try editing that file down to:

```bash
#!/...keep original shebang here
import re
import sys
from project._cli.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

If it's *not* just the setuptools-generated script that fails, can you please provide the full steps needed to produce the error?

**Comment by avatar-lavventura** [comment] 2022-03-07 17:20
Does correspoing `requirements.txt` have `zope_traversing==4.4.1` in it right not `zope.traversal`?  

> When you setuptools-generated console script?
Yes. When I use the one under `~/venv/bin/`, :  `/home/alper/venv/bin/package_name`

I can try to generate example from my main repo.

I think, `setuptools` here it parses all the packages:

```
with open(requirements_filename, "r") as f:
    requirements = list(map(str.strip, f.read().split("\n")))[:-1]
```
where `requirements ` contains `zope_traversing` and other package names. Afterwards `install_requires=requirements,` checks whether `zope_traversing` is installed but instead `zope.traversing` is installed so it .

**Comment by AndydeCleyre** [comment] 2022-03-07 17:29
The dots, underscores, and dashes are all interchangeable for package names. `pip-compile` is always writing with the dash form. Have you read through #1576 yet?

Can you try editing the launch script as above?

**Comment by AndydeCleyre** [comment] 2022-03-07 20:23
I hate to be so repetitive, but do please read the discussion at #1576. I think this issue here is really a duplicate of that one.

> How could I use the launch script above?

If you paste here the content of the launcher script that setuptools generates on your machine, I'll edit it to remove complications inserted by setuptools, for you to test.

> That's not correct

Ah, by "always" I didn't mean for all of history, I just meant in all cases with current versions. Yes the behavior changed recently, matching similar changes within pip itself.

**Comment by avatar-lavventura** [comment] 2022-03-07 20:32
Yeah issues seem duplicate of each other.

I think that behavior change causing all the issues. For example correct version should be: `aspy.refactor-imports` but pip-compile changes it into `aspy-refactor-imports`. 

```
$ pip freeze | grep aspy.refactor
aspy.refactor-imports==2.1.1
```

**Comment by AndydeCleyre** [comment] 2022-03-07 21:45
I'm not convinced there's good reason to change this convergence of canonicalized names, but will keep tracking the problems at #1576 until they are resolved one way or another. I'll close this one in favor of that one for now, and I've gone ahead and opened pypa/setuptools#3157

**Closed by AndydeCleyre** 2022-03-07 21:45 UTC
