### ISSUE TITLE
pip-compile ignores package marked with python_version via setup.py

### ISSUE THREAD

**Issue by Abhishek-Dev09** [jazzband/pip-tools#1202] opened 2020-08-13 11:32 UTC
Environment Versions
OS Type
Python version: 3.6.8
pip version: 20.1.1
pip-tools version: 5.2.1

Steps to replicate
`pip-compile `

setup.py 

'ftfy <  5.0.0; python_version == "2.7"',
'ftfy>=  5.0.0; python_version > "3"',

Actual result: requirement.txt missed above package .

Expected result - requirement.txt must contains above package based on python version.

**Comment by atugushev** [comment] 2020-08-19 01:48
Duplicate of #1139.

**Closed** 2020-08-19 01:49 UTC
Labels: duplicate, markers, setuptools
