### ISSUE TITLE
pip-tools logger should always go to stderr

### ISSUE THREAD

**Issue by cjerdonek** [jazzband/pip-tools#362] opened 2016-05-16 00:36 UTC
I noticed that pip-tools's logger (called [`LogContext` here](https://github.com/nvie/pip-tools/blob/d521d766113e69ea0a10017bb968d3b3bb242e5f/piptools/logging.py#L10)) sometimes writes to stdout (depending on the log level).

It would be best if the logger always writes to stderr since a logger is for monitoring / diagnostic purposes, and its messages can interfere if one is trying to capture the "output" portion of running the script. This would help in addressing some of the other pip-tools issues related to stdout and stderr.

In cases where stdout is needed, a separate function can be used (e.g. `print()`). This would help in separating pip-tools's "API" (stdout) from its diagnostic / progress reporting (stderr).

**Comment by jdufresne** [comment] 2017-05-31 13:32
This looks like a duplicate of #353

**Comment by cjerdonek** [comment] 2017-05-31 18:51
Issue #353 is related in that fixing this issue could very well wind up fixing that one. But, for example, it's possible that not all of `pip-compile --verbose`'s output uses the `LogContext` class (which is what this issue covers). We'd want to check that separately as part of issue #353, and maybe even also have a different type of test case (e.g. an end-to-end test using the CLI).

**Comment by atugushev** [comment] 2019-09-15 23:05
Fixed in #834.

**Closed by atugushev** 2019-09-15 23:05 UTC
Labels: PR wanted, log/console output
