### ISSUE TITLE
Requirements of vcs url requirement are not commented in the output of pip-compile

### ISSUE THREAD

**Issue by piotr-dobrogost** [jazzband/pip-tools#423] opened 2016-12-13 09:30 UTC
When there's a vcs url (editable, as non-editable ones are currently not supported, issue #355) requirement in the input file (for example `-e hg+ssh://user@server.local/packageX@packageX_1-0-0#egg=packageX`) then in the output of `pip-compile` all requirements of this vcs url input requirement are not commented with information on what depends on them. In the below example `pytz` has comment with the information on what requires it but `pyYAML` does not.

```
pytz==2016.10             # via tzlocal
pyYAML==3.12         
```

**Comment by jonafato** [comment] 2017-07-24 17:17
This appears to be a duplicate of #293.

**Comment by vphilippon** [comment] 2017-11-24 00:52
duplicate of #293

**Closed by vphilippon** 2017-11-24 00:52 UTC
