### ISSUE TITLE
Bug in handling extra dependencies of extra dependencies.

### ISSUE THREAD

**Issue by SnichOne** [jazzband/pip-tools#1548] opened 2022-01-05 11:20 UTC
`pip-compile` fails handling extra dependency of an extra dependency: e.g., pip-compile of `boto3[crt]` results in `botocore` but it should be `botocore[crt]`. 

#### Environment Versions

1. OS Type: `Arch Linux 5.15.11-arch2-1`
1. Python version: `Python 3.9.9`
1. pip version: `pip 21.3.1 (python 3.9)`
1. pip-tools version: `pip-compile, version 6.4.0`

#### Steps to replicate

1. `echo "boto3[crt]" | pip-compile - -qo- `

#### Expected result

```
#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --output-file=- -
#
awscrt==0.12.5
    # via botocore
boto3[crt]==1.20.28
    # via -r -
botocore[crt]==1.23.28
    # via
    #   boto3[crt]
    #   s3transfer
jmespath==0.10.0
    # via
    #   boto3
    #   botocore
python-dateutil==2.8.2
    # via botocore
s3transfer==0.5.0
    # via boto3
six==1.16.0
    # via python-dateutil
urllib3==1.26.7
    # via botocore
```

#### Actual result

```
#
# This file is autogenerated by pip-compile with python 3.9
# To update, run:
#
#    pip-compile --output-file=- -
#
boto3[crt]==1.20.28
    # via -r -
botocore==1.23.28
    # via
    #   boto3
    #   s3transfer
jmespath==0.10.0
    # via
    #   boto3
    #   botocore
python-dateutil==2.8.2
    # via botocore
s3transfer==0.5.0
    # via boto3
six==1.16.0
    # via python-dateutil
urllib3==1.26.7
    # via botocore
```

**Comment by richafrank** [comment] 2022-01-08 20:16
Thanks @SnichOne ! This looks to be a duplicate of the still-open #603. I'll close this, but please re-open if you disagree.

**Closed by richafrank** 2022-01-08 20:16 UTC
