### ISSUE TITLE
Install an extra via environment markers

### ISSUE THREAD

**Issue by matrixise** [jazzband/pip-tools#1555] opened 2022-01-24 10:14 UTC
#### Environment Versions

1. OS Type - Linux, macOS
1. Python version: `$ python -V` 3.10.1
1. pip version: `$ pip --version` 21.3.1
1. pip-tools version: `$ pip-compile --version` 6.4.0

#### Steps to replicate

in a `requirements.in`, I try to install `spacy` for non M1 chip and `spacy[apple]` for M1
```
spacy; platform_machine != 'arm64'
spacy[apple]; sys_platform == 'darwin' and platform_machine == 'arm64'
```

#### Expected result

in the `requirements.txt`
```
spacy; platform_machine != 'arm64'
spacy[apple]; sys_platform == 'darwin' and platform_machine == 'arm64'
```

#### Actual result

```
spacy; platform_machine != 'arm64'
```

I would like to be honest, I am not sure about the syntax for the installation of an extra via the environment markers. Do you have some advices?

Thank you

**Comment by AndydeCleyre** [comment] 2022-02-08 22:35
I think this is currently working as intended.. Might this be a duplicate of #1553 or #1326?

**Comment by AndydeCleyre** [comment] 2022-02-16 17:12
I'm going to close this in favor of concentrating relevant discussion at #1326, thanks!

**Closed by AndydeCleyre** 2022-02-16 17:12 UTC
