### ISSUE TITLE
pip-sync doesn't report an error if packages fail to install?

### ISSUE THREAD

**Issue by vlovich** [jazzband/pip-tools#687] opened 2018-10-04 19:18 UTC
Describe the issue briefly here.
I have let's say 10 packages that pip-sync would install into a virtual environment but some of them fail to compile due to missing bdist_wheel.  The packages at the beginning & end install just fine.  I would expect pip-sync to exit with an error code but instead it completes without error.  This makes it tough to automate as our tools think pip-sync is successful when it's not actually so.

##### Environment Versions

1. OS Type: OSX 10.13.1
1. Python version: `$ python -V` 3.7.0
1. pip version:  `$ pip --version` 18.0
1. pip-tools version: `$ pip-compile --version` 2.0.2

##### Steps to replicate

1. Run pip-sync so that 1 package in the middle of a set of packages fails to install successfully.

##### Expected result
pip-sync should exit with a non-0 exit-code.

##### Actual result
pip-sync exits with an error code of 0.

**Comment by vphilippon** [comment] 2018-10-05 18:35
Hello @vlovich,

I'm not able to reproduce the error on Windows, and I don't have an OSX machine to test.
I tested with both pip-tools v2.0.0 and v3.0.0, and if any of the package fail to install, I receive a non-0 return code.

Can you give a sample `requirements.txt`?

**Comment by vlovich** [comment] 2018-10-09 23:41
It wasn't a problem with the requirements.txt.  It was some issue with native packages failing to compile due to bdist_wheel issues.

**Comment by vlovich** [comment] 2018-10-11 23:28
Namely, inflection==0.3.1 results in:

```
Requirement already satisfied: setuptools in ./tools/cmdline/python-env/lib/python3.6/site-packages (from protobuf==3.6.0) (40.4.3)
Building wheels for collected packages: inflection
  Running setup.py bdist_wheel for inflection ... error
  Complete output from command /usr/local/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xs/md937lms7k79c0fgz71blqh400_dy5/T/pip-install-4y9cs62v/inflection/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/xs/md937lms7k79c0fgz71blqh400_dy5/T/pip-wheel-zwf3wbs7 --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for inflection
  Running setup.py clean for inflection
Failed to build inflection
```

but the command exits with success.

**Comment by atugushev** [comment] 2019-09-19 16:12
It looks like you didn't install a `wheel` package, that's why pip unable to build wheels for it. However, pip installed the package from the source and considered the op as successful. 

I'll close this since it doesn't look like there's any action required regarding pip-tools. Consider opening an issue on pip's tracker if you would like. Thanks for the issue!

**Closed by atugushev** 2019-09-19 16:12 UTC
Labels: needs more info
