### ISSUE TITLE
Duplicate package entries in compiled requirements with pip 8.1.2 and pip-compile 1.7.0

### ISSUE THREAD

**Issue by bwells** [jazzband/pip-tools#376] opened 2016-07-07 00:43 UTC
I'm unclear if this a bug within pip or pip tools. If multiple valid names for a package are included in a requirements list then the canonical name is included twice in the compiled requirements file. In our case we had 'factory-boy' and 'factory_boy' both included in separate files of a requirements file chain. 

This is not true with pip==8.1.1 for either pip-tools==1.6.5 or 1.7.0. It is only true with pip==8.1.2 and pip-tools==1.7.0
##### Steps to replicate
1. Create `requirements.in` with `factory_boy` and `factory-boy` on separate lines
2. `pip-compile requirements.in`
##### Expected result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
factory-boy==2.7.0
fake-factory==0.5.8       # via factory-boy
python-dateutil==2.5.3    # via fake-factory
six==1.10.0               # via fake-factory, python-dateutil
```
##### Actual result

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
factory-boy==2.7.0
factory-boy==2.7.0
fake-factory==0.5.8       # via factory-boy
python-dateutil==2.5.3    # via fake-factory
six==1.10.0               # via fake-factory, python-dateutil
```

See that `factory-boy==2.7.0` is included twice.

**Comment by dimka665** [comment] 2016-07-19 15:21
Same issue

requirements.in:
```
django-libsass == 0.7
django_compressor == 2.0
```
pip-compile requrements.in
```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file t.txt t.in
#
django-appconf==1.0.2     # via django-compressor, django_compressor
django-compressor==1.6    # via django-libsass
django-libsass==0.7
django_compressor==2.0    # via django-libsass
libsass==0.11.1           # via django-libsass
rcssmin==1.0.6            # via django_compressor
rjsmin==1.0.12            # via django_compressor
six==1.10.0               # via libsass
```

**Comment by gbataille** [comment] 2016-09-06 05:42
exactly the same for me :(

**Comment by Cabalist** [comment] 2016-09-06 22:36
Same here for Flask-Migrate:

```
flask-script==2.0.5       # via flask-migrate
flask-script==2.0.5       # via flask-migrate
```

**Comment by milin** [comment] 2016-09-19 21:09
Can confirm.

```
autopep8==1.1.1
babel==2.3.4
backports-abc==0.4        # via tornado
backports.ssl-match-hostname==3.4.0.2
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.4.1
billiard==3.3.0.23        # via celery
bleach==1.4.2
```

**Comment by Groxx** [comment] 2017-01-19 00:02
Still a problem with 1.8.0 fwiw

**Comment by coriolinus** [comment] 2017-02-16 15:41
Same issue:

```shell
$ pip-compile --version && cat requirements.in && pip-compile --dry-run
pip-compile, version 1.8.0
pip-tools               # needed for pip-compile and pip-sync
Django                  # fundamental web framework
djangorestframework     # REST framework
django-storages         # Used for modeling S3 objects within Django models
psycopg2                # Used for interacting with Postgres DBs
boto                    # direct interface to AWS, used by Django
boto3                   # modern direct interface to AWS, used by our code
hypothesis[django]      # testing framework

bcrypt                  # allows django to read bcrypt-encrypted passwords
croniter                # get datetime of next run of a cron job
django-choices          # Enum-like objects for multiple choice fields
django-extra-fields     # for Base64ImageField
django-push-notifications # Push notifications helper
django-rest-swagger     # Alternate documentation generator for DRF
django-ses              # email manager which routes emails over AWS SES
geopy                   # geographic functions for i.e. distance between two lat, long points
googlemaps              # geo functions with a more detailed API for neighborhoods etc
mailchimp3              # client library for Mailchimp API v3.0
Pillow                  # image processing library so `ImageField`s work
PyYAML                  # parse YAML files
responses               # test helper to mock out HTTP within the Requests library
social-auth-core        # AKA python-social-auth. Goal here is to move away from RSA, which
social-auth-app-django  # is a thin wrapper over this functionality anyway.
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
bcrypt==3.1.2
boto3==1.4.4
boto==2.45.0
botocore==1.5.12          # via boto3, s3transfer
cffi==1.9.1               # via bcrypt
click==6.7                # via pip-tools
cookies==2.2.1            # via responses
coreapi==2.2.4            # via django-rest-swagger, openapi-codec
coreschema==0.0.4         # via coreapi
croniter==0.3.15
defusedxml==0.5.0         # via python3-openid, social-auth-core
django-choices==1.5.0
django-extra-fields==0.9
django-push-notifications==1.4.1
django-rest-swagger==2.1.1
django-ses==0.8.1
django-storages==1.5.2
django==1.10.5
djangorestframework==3.5.4
docutils==0.13.1          # via botocore
first==2.0.1              # via pip-tools
geopy==1.11.0
googlemaps==2.4.5
hypothesis[django]==3.6.1
itypes==1.1.0             # via coreapi
jinja2==2.9.5             # via coreschema
jmespath==0.9.1           # via boto3, botocore
mailchimp3==2.0.7
markupsafe==0.23          # via jinja2
oauthlib==2.0.1           # via requests-oauthlib, social-auth-core
olefile==0.44             # via pillow
openapi-codec==1.3.1      # via django-rest-swagger
pillow==4.0.0
pip-tools==1.8.0
psycopg2==2.6.2
pycparser==2.17           # via cffi
pyjwt==1.4.2              # via social-auth-core
python-dateutil==2.6.0    # via botocore, croniter
python-dateutil==2.6.0    # via botocore, croniter
python3-openid==3.0.10    # via social-auth-core
pytz==2016.10             # via hypothesis
pyyaml==3.12
requests-oauthlib==0.8.0  # via social-auth-core
requests==2.11.1          # via coreapi, googlemaps, mailchimp3, requests-oauthlib, responses, social-auth-core
responses==0.5.1
s3transfer==0.1.10        # via boto3
simplejson==3.10.0        # via django-rest-swagger
six==1.10.0               # via bcrypt, pip-tools, python-dateutil, responses, social-auth-app-django, social-auth-core
social-auth-app-django==1.1.0
social-auth-core==1.2.0
uritemplate==3.0.0        # via coreapi
```
Note that `python-dateutil` appears twice.

**Comment by IlyaSemenov** [comment] 2017-03-16 05:00
On a different set of requirements:

```console
$ cat requirements.in
arrow
rq-scheduler
$ cat requirements.txt
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
arrow==0.10.0
click==6.7                # via rq
croniter==0.3.16          # via rq-scheduler
python-dateutil==2.6.0    # via arrow, croniter
python-dateutil==2.6.0    # via arrow, croniter
redis==2.10.5             # via rq
rq-scheduler==0.7.0
rq==0.7.1                 # via rq-scheduler
six==1.10.0               # via python-dateutil
$ pip-compile --version
pip-compile, version 1.8.0
$ pip --version
pip 9.0.1 from /Users/semenov/.pyenv/versions/3.5.2/envs/test/lib/python3.5/site-packages (python 3.5)
```

**Comment by davidovich** [comment] 2017-03-21 15:52
@IlyaSemenov This is fixed in the upcoming 1.8.1 (currently as an rc3) 

I cannot reproduce with 1.8.1rc3. 

Can you verify that it also fixes your issue? Thanks.

**Comment by IlyaSemenov** [comment] 2017-03-22 02:45
@davidovich I confirm that the problem doesn't repeat with 1.8.1rc3 (I actually was unable to reproduce it on 1.8.0 as well — probably due to package updates, but quickly reproduced with `arrow` + `croniter`, which however also worked correctly in 1.8.1rc3).

**Comment by davidovich** [comment] 2017-03-22 02:52
Thanks, closing then.

**Closed by davidovich** 2017-03-22 02:52 UTC
