### ISSUE TITLE
pip-compile unnecessarily chooses a package version which is uncompatible with the installed Python 2 version

### ISSUE THREAD

**Issue by alanoe** [jazzband/pip-tools#1100] opened 2020-04-01 23:52 UTC
summary: pip-compile unnecessarily chooses a Pygments package version which runs only on Python 3 when running in a system with Python 2.7

#### Environment Versions

1. OS: Ubuntu 16.04
1. Python version: 2.7.12
1. pip version:  9.0.3
1. pip-tools version: 4.5.1

#### Steps to replicate

1. Create a requirements.in file with the following content:

  coverage==4.4 
  diff-cover==0.9.8
  oauthlib==2.1.0 
  pylint-plugin-utils==0.3
  requests-oauthlib==1.1.0
  six==1.11.0 
  splinter==0.9.0 
  urllib3<1.24 
  Markdown==2.6.11

2. Run: pip-compile -v --upgrade -o requirements.txt requirements.in

#### Expected result

requirements.txt must be created without errors

#### Actual result

```
ROUND 1 
(....)
Finding the best candidates:
  found candidate coverage==4.4 (constraint was ==4.4)
  found candidate diff-cover==0.9.8 (constraint was ==0.9.8)
  found candidate markdown==2.6.11 (constraint was ==2.6.11)
  found candidate oauthlib==2.1.0 (constraint was ==2.1.0)
  found candidate pylint-plugin-utils==0.3 (constraint was ==0.3)
  found candidate requests-oauthlib==1.1.0 (constraint was ==1.1.0)
  found candidate six==1.11.0 (constraint was ==1.11.0)
  found candidate splinter==0.9.0 (constraint was ==0.9.0)
  found candidate urllib3==1.23 (constraint was <1.24)
Finding secondary dependencies:
  diff-cover==0.9.8 not in cache, need to check index
  diff-cover==0.9.8         requires jinja2-pluralize, Jinja2>=2.7.1, pygments, six>=1.6.1
  coverage==4.4 not in cache, need to check index
  coverage==4.4             requires -
  six==1.11.0               requires -
New dependencies found in this round:
  adding [u'jinja2', '>=2.7.1', '[]']
  adding [u'jinja2-pluralize', '', '[]']
  adding [u'pygments', '', '[]']
  adding [u'six', '>=1.6.1', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

ROUND 2                           
Current constraints:
  coverage==4.4 
  diff-cover==0.9.8 
  Jinja2>=2.7.1 
  jinja2-pluralize 
  Markdown==2.6.11 
  oauthlib==2.1.0 
  pygments 
  pylint-plugin-utils==0.3 
  requests-oauthlib==1.1.0 
  six==1.11.0,>=1.6.1 
  splinter==0.9.0 
  urllib3<1.24 

Finding the best candidates:
  found candidate coverage==4.4 (constraint was ==4.4)
  found candidate diff-cover==0.9.8 (constraint was ==0.9.8)
  found candidate jinja2==2.11.1 (constraint was >=2.7.1)
  found candidate jinja2-pluralize==0.3.0 (constraint was <any>)
  found candidate markdown==2.6.11 (constraint was ==2.6.11)
  found candidate oauthlib==2.1.0 (constraint was ==2.1.0)
  found candidate pygments==2.6.1 (constraint was <any>)
  found candidate pylint-plugin-utils==0.3 (constraint was ==0.3)
  found candidate requests-oauthlib==1.1.0 (constraint was ==1.1.0)
  found candidate six==1.11.0 (constraint was ==1.11.0,>=1.6.1)
  found candidate splinter==0.9.0 (constraint was ==0.9.0)
  found candidate urllib3==1.23 (constraint was <1.24)

Finding secondary dependencies:
  jinja2==2.11.1 not in cache, need to check index
  jinja2==2.11.1            requires MarkupSafe>=0.23
  jinja2-pluralize==0.3.0 not in cache, need to check index
  jinja2-pluralize==0.3.0   requires inflect>=0.2.4, jinja2>=2.4
  pygments==2.6.1 not in cache, need to check index
Traceback (most recent call last):
(...)
pip.exceptions.UnsupportedPythonVersion: Pygments requires Python '>=3.5' but the running Python is 2.7.12
```

If any Pygments version is allowed, why does pip-compile choose one which requires Python >= 3.5 instead of choosing one which runs in Python 2.7? I'm not familiar with pip-compile internals or pip internals, so this question possibly has an obvious answer.

**Comment by atugushev** [comment] 2020-04-02 05:51
Hello @alanoe,

Thanks for the issue! Could not reproduce it on docker:

```console
$ docker run --rm -it python:2.7-slim /bin/bash

root@91263d5bc366:/# pip install pip==9.0.3 pip-tools

root@91263d5bc366:/# python --version
Python 2.7.17

root@91263d5bc366:/# pip --version
pip 9.0.3 from /usr/local/lib/python2.7/site-packages (python 2.7)

root@91263d5bc366:/# pip-compile --version
pip-compile, version 4.5.1

root@91263d5bc366:/# cat requirements.in
coverage==4.4
diff-cover==0.9.8
oauthlib==2.1.0
pylint-plugin-utils==0.3
requests-oauthlib==1.1.0
six==1.11.0
splinter==0.9.0
urllib3<1.24
Markdown==2.6.11

root@91263d5bc366:/# pip-compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
astroid==1.6.6            # via pylint
backports.functools-lru-cache==1.6.1  # via astroid, isort, pylint
certifi==2019.11.28       # via requests
chardet==3.0.4            # via requests
configparser==4.0.2       # via importlib-metadata, pylint
contextlib2==0.6.0.post1  # via importlib-metadata, zipp
coverage==4.4             # via -r requirements.in
diff-cover==0.9.8         # via -r requirements.in
enum34==1.1.10            # via astroid
futures==3.3.0            # via isort
idna==2.9                 # via requests
importlib-metadata==1.6.0  # via inflect
inflect==3.0.2            # via jinja2-pluralize
isort==4.3.21             # via pylint
jinja2-pluralize==0.3.0   # via diff-cover
jinja2==2.11.1            # via diff-cover, jinja2-pluralize
lazy-object-proxy==1.4.3  # via astroid
markdown==2.6.11          # via -r requirements.in
markupsafe==1.1.1         # via jinja2
mccabe==0.6.1             # via pylint
oauthlib==2.1.0           # via -r requirements.in, requests-oauthlib
pathlib2==2.3.5           # via importlib-metadata
pygments==2.5.2           # via diff-cover
pylint-plugin-utils==0.3  # via -r requirements.in
pylint==1.9.5             # via pylint-plugin-utils
requests-oauthlib==1.1.0  # via -r requirements.in
requests==2.23.0          # via requests-oauthlib
scandir==1.10.0           # via pathlib2
selenium==3.141.0         # via splinter
singledispatch==3.4.0.3   # via astroid, pylint
six==1.11.0               # via -r requirements.in, astroid, diff-cover, pathlib2, pylint, singledispatch
splinter==0.9.0           # via -r requirements.in
urllib3==1.23             # via -r requirements.in, requests, selenium
wrapt==1.12.1             # via astroid
zipp==1.2.0               # via importlib-metadata
```

Could you attach the full output from `pip-compile --rebuild --verbose`?

**Comment by AndydeCleyre** [comment] 2020-04-26 03:01
This may happen if the problematic `pygments` pin is already in the `txt` before compilation -- for example if you run `pip-compile` in a py3 env before doing so in a py2 env. If it's a py2 project, you can delete the `txt` and only run `pip-compile` with py2.

@atugushev -- bug or no bug?

**Comment by atugushev** [comment] 2020-04-26 05:45
I see. It's not a bug then IMO, since there should be a separate `requirememts-py{2,3}.txt` for each major python version. See also [this article](https://github.com/jazzband/pip-tools#cross-environment-usage-of-requirementsinrequirementstxt-and-pip-compile).

**Comment by atugushev** [comment] 2021-03-13 04:13
I hope the above helped. It's been some time so I will close this issue now, but please don't hesitate to reach out if you have any other issues. Thanks for the issue!

**Closed by atugushev** 2021-03-13 04:13 UTC
Labels: awaiting response, support
