### ISSUE TITLE
pip-compile loses VCS egg name from setup.py

### ISSUE THREAD

**Issue by cbows** [jazzband/pip-tools#902] opened 2019-09-20 11:45 UTC
When using a simple layered dependency workflow (production->development requirements) the egg name specified in `setup.py` is missing in `requirements.txt`. This causes duplicate entries of same vcs url in `dev-requirements.txt` if a vcs dependency itself depends on another vcs dependency.

#### Environment Versions

OS Type: Ubuntu GNU/Linux v18.04
Python version: 3.7.4
pip version:  19.2.3
pip-tools version: 4.1.0

#### Steps to replicate

1. Create setup.py with vcs url in `install_requires`

```python
from setuptools import setup
setup(
    ...,
    install_requires=['mypackage @ <vcs_url>'],
    ...,
)
```

2. Compile `requirements.txt`.

#### Expected result

```ini
<vcs_url>#egg=mypackage
```

#### Actual result

```ini
<vcs_url>
```

#### Workaround

Specifying the egg name explicitly in vcs url in `setup.py`

```python
from setuptools import setup
setup(
    ...,
    install_requires=['mypackage @ <vcs_url>#egg=mypackage'],
    ...,
)
```

will produce the expected result.

**Comment by atugushev** [comment] 2019-09-23 23:41
Hello @cbows,

Thanks for bringing up this! 

FTR and truly curious:
- there is a related issue #854 and it looks like the proper support of `name@url` is going to be released in `pip==19.3`. See https://github.com/pypa/pip/pull/6203.
- `mypackage @ <vcs_url>` dependency specification described in [PEP 508](https://www.python.org/dev/peps/pep-0508/).
- egg framents specification described in [pip install](https://pip.pypa.io/en/stable/reference/pip_install/#working-out-the-name-and-version) documentation.

**Comment by atugushev** [comment] 2020-01-01 18:34
FTR, relative [discussion about PEP 508](https://discuss.python.org/t/what-is-the-correct-interpretation-of-path-based-pep-508-uri-reference/2815) on python packaging forum.

**Comment by sambarluc** [comment] 2021-10-04 11:21
I guess the same question I posted in https://github.com/jazzband/pip-tools/issues/1111#issuecomment-933325877 is relevant here too.

**Comment by atugushev** [comment] 2022-12-14 00:39
Can't reproduce anymore with `pip-tools-6.11.0`. I believe it was fixed in https://github.com/jazzband/pip-tools/pull/1455.

```python
# setup.py
from setuptools import setup
setup(
    name="bar",
    version="0.1",
    install_requires=['six @ git+https://github.com/atugushev/six'],
)
```


```console
$ pip-compile --resolver=backtracking
#
# This file is autogenerated by pip-compile with Python 3.11
# by the following command:
#
#    pip-compile --resolver=backtracking
#
six @ git+https://github.com/atugushev/six
    # via bar (setup.py)
```

So I close this as completed. Feel free to reopen if you think that the issue is not resolved. Thanks!

**Closed by atugushev** 2022-12-14 00:39 UTC
Labels: bug, setuptools
