### ISSUE TITLE
pip-compile does not find extras

### ISSUE THREAD

**Issue by q0w** [jazzband/pip-tools#1993] opened 2023-10-02 07:56 UTC
Pip-compile does not find `dj_rest_auth` extras. (`pip install -r requirements.in` works as expected.)
#### Environment Versions

1. OS Type: Linux
1. Python version: `$ python -V` 3.11.5
1. pip version: `$ pip --version`: 23.2.1
1. pip-tools version: `$ pip-compile --version` 7.3.0

#### Steps to replicate
```
echo "dj_rest_auth[with_social]" > requirements.in
pip-compile --strip-extras --allow-unsafe --no-config
```
```
WARNING: dj-rest-auth 5.0.1 does not provide the extra 'with_social'
```
#### Expected result
requirements.txt contains `django-allauth`.

#### Actual result
There is no `django-allauth` in requirements.txt

**Comment by q0w** [comment] 2023-10-04 12:49
pip>22 also does not find `with_social` extra. It seems pip now expects normalized extra name- `with-social`

**Comment by terencehonles** [comment] 2023-10-06 21:17
if that's the case then you should either open an issue with pip or close this since it would be working as intended. This tool uses pip itself and will mimic that behavior.

**Comment by q0w** [comment] 2023-10-07 05:32
Yea, I know. Just forgot to close.

**Closed** 2023-10-07 05:32 UTC

**Comment by naisanzaa** [comment] 2024-05-12 20:10
did you find a solution?

**Comment by q0w** [comment] 2024-05-13 04:53
I replaced `with_social` with `with-social` myself in requirements.in
