### ISSUE TITLE
NotADirectoryError when running --generate-hashes

### ISSUE THREAD

**Issue by DeastinY** [jazzband/pip-tools#512] opened 2017-05-23 09:50 UTC
Running `pip-compile` works flawless, but pip-compile `--generate-hashes` produces the following error:

> Traceback (most recent call last):
>   File "/home/ric/.local/bin/pip-compile", line 11, in <module>
>     sys.exit(cli())
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ric/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/scripts/compile.py", line 186, in cli
>     hashes = resolver.resolve_hashes(results)
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/resolver.py", line 77, in resolve_hashes
>     return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/resolver.py", line 77, in <dictcomp>
>     return {ireq: self.repository.get_hashes(ireq) for ireq in ireqs}
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 169, in get_hashes
>     for candidate in matching_candidates
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 169, in <setcomp>
>     for candidate in matching_candidates
>   File "/home/ric/.local/lib/python3.5/site-packages/piptools/repositories/pypi.py", line 176, in _get_file_hash
>     download_dir=tmpdir, only_download=True, session=self.session
>   File "/usr/lib/python3/dist-packages/pip/download.py", line 821, in unpack_url
>     hashes=hashes
>   File "/usr/lib/python3/dist-packages/pip/download.py", line 663, in unpack_http_url
>     unpack_file(from_path, location, content_type, link)
>   File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 623, in unpack_file
>     untar_file(filename, location)
>   File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 595, in untar_file
>     with open(path, 'wb') as destfp:
> NotADirectoryError: [Errno 20] Not a directory: '/tmp/tmprk7taktxbuild/LICENSE/LICENSE_STIX'
> 

##### Environment Versions

1. Ubuntu 16.04
1. Python 3.5.3
1. pip 9.0.1
1. pip-compile 1.9.0

This is my `requirements.in` file:

> 
> seaborn==0.7.1
> pandas==0.20.1
> numpy==1.12.1
> scipy==0.19.0
> tqdm==4.11.2
> matplotlib==2.0.2
>

**Comment by proinsias** [comment] 2017-05-30 18:30
I encountered the same error – I believe it's `matplotlib` – see https://github.com/jheinen/matplotlib/blob/master/LICENSE/LICENSE_STIX .

**Comment by di** [comment] 2017-08-30 16:11
Seems to be a duplicate of #438.

**Closed** 2017-09-27 13:51 UTC

**Comment by cooperlees** [comment] 2018-01-05 17:15
I hit this error too. I thank @DeastinY to having the exception in the issue to make this much more Google-a-ble ... Save me manual debugging of the code :) <3

Can confirm 1.11.0 fixed my problems.
