### ISSUE TITLE
 Expected a pinned InstallRequirement, got unknown : WeasyPrint==50

### ISSUE THREAD

**Issue by portedison** [jazzband/pip-tools#1218] opened 2020-10-30 01:15 UTC
#### Environment Versions

1. OS Type
1. Python version: Python 3.6.0 (using pyenv)
1. pip version:  pip 20.2.4
1. pip-tools version: 5.3.1

#### Steps to replicate

1. create requirements.in including 'WeasyPrint==50'
2. run pip-compile --output-file=requirements.txt requirements.in

#### Result
`raise TypeError("Expected a pinned InstallRequirement, got {}".format(ireq))
TypeError: Expected a pinned InstallRequirement, got unknown from https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz#sha256=f1c0c5878f74ac9ccb5d48b2601fcc75390c881ce476e79f4cfedd288b1b05db (from weasyprint==50->-r requirements.in (line 28))`

**Comment by portedison** [comment] 2020-11-02 03:04
Ah sorry this created a duplicate - https://github.com/jazzband/pip-tools/issues/1219

**Comment by AndydeCleyre** [comment] 2020-11-06 05:13
I was unable to reproduce here on Arch Linux, with the same versions, as well as with Python `3.8.6`. 

- What OS/distro are you using?
- Are you sure about those replication steps?

```ini
cairocffi==1.2.0          # via cairosvg, weasyprint
cairosvg==2.5.0           # via weasyprint
cffi==1.14.3              # via cairocffi, weasyprint
cssselect2==0.4.1         # via cairosvg, weasyprint
defusedxml==0.6.0         # via cairosvg
html5lib==1.1             # via weasyprint
pillow==8.0.1             # via cairosvg
pycparser==2.20           # via cffi
pyphen==0.10.0            # via weasyprint
six==1.15.0               # via html5lib
tinycss2==1.1.0           # via cairosvg, cssselect2, weasyprint
weasyprint==50            # via -r requirements.in
webencodings==0.5.1       # via cssselect2, html5lib, tinycss2

# The following packages are considered to be unsafe in a requirements file:
# setuptools
```

**Comment by portedison** [comment] 2020-11-08 20:42
Mac OS 10.15.4
Can you explain what the expected  'pinned InstallRequirement' should be? Maybe I could run a few tests. It seems to be triggering from cairocffi-1.2.0 (seen in duplicate task)

**Comment by AndydeCleyre** [comment] 2020-11-10 06:10
Here's a guess: maybe you have a (non-pip-tools-generated) `requirements.txt` file already, with something that surprises `pip-compile`.

If `requirements.txt` does indeed already exist, please paste it here, and rename/move/delete it before you try compiling again.

**Comment by AndydeCleyre** [comment] 2021-01-01 17:33
@portedison Are you still interested in figuring this out?

**Comment by AndydeCleyre** [comment] 2021-01-20 21:16
Hi @portedison, 

It's been a couple months since you've been here, so I'm going to close this, as no one can reproduce the problem with the information we have.

Please let us know if you can provide any more info, and I'll re-open. Thanks!

**Closed by AndydeCleyre** 2021-01-20 21:16 UTC
Labels: awaiting response, support
