### ISSUE TITLE
pip-compile --version raise an exception

### ISSUE THREAD

**Issue by luzfcb** [jazzband/pip-tools#1417] opened 2021-06-11 16:35 UTC
pip-compile --version raise an exception on all python versions.

#### Environment Versions

1. OS Type: Linux
1. Python version: python3.9
1. pip version: pip 21.0.2
1. pip-tools version: 6.1.0

#### Steps to replicate

1. Install "pip-tools==6.1.0"
2. pip-compile --version

I also tested on python3.6, 3.7, and 3.8 and the issue is the same.

#### Expected result

```bash
$ pip-compile --version
pip-compile, version 6.1.0

```

#### Actual result

```bash
$ mktmpenv -p python3.9
created virtual environment CPython3.9.2.final.0-64 in 110ms
  creator CPython3Posix(dest=/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/luzfcb/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==56.2.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
virtualenvwrapper.user_scripts creating /home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/preactivate
virtualenvwrapper.user_scripts creating /home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/postactivate
virtualenvwrapper.user_scripts creating /home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/get_env_details
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-c9222a477c8f9ca) luzfcb@fabio-pc:~/.virtualenvs/tmp-c9222a477c8f9ca
$ pip install "pip-tools==6.1.0"
Collecting pip-tools==6.1.0
  Using cached pip_tools-6.1.0-py3-none-any.whl (44 kB)
Collecting click>=7
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting pep517
  Using cached pep517-0.10.0-py2.py3-none-any.whl (19 kB)
Requirement already satisfied: pip>=20.3 in ./lib/python3.9/site-packages (from pip-tools==6.1.0) (21.0.1)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: toml, pep517, click, pip-tools
Successfully installed click-8.0.1 pep517-0.10.0 pip-tools-6.1.0 toml-0.10.2
WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
You should consider upgrading via the '/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/python -m pip install --upgrade pip' command.

(tmp-c9222a477c8f9ca) luzfcb@fabio-pc:~/.virtualenvs/tmp-c9222a477c8f9ca
$ pip-compile --version
Traceback (most recent call last):
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/decorators.py", line 379, in callback
    version = metadata.version(package_name)  # type: ignore
  File "/home/luzfcb/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/home/luzfcb/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/luzfcb/.pyenv/versions/3.9.2/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: piptools

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 1061, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 923, in make_context
    self.parse_args(ctx, args)
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 1379, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 2364, in handle_parse_result
    value = self.process_value(ctx, value)
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/core.py", line 2326, in process_value
    value = self.callback(ctx, self, value)
  File "/home/luzfcb/.virtualenvs/tmp-c9222a477c8f9ca/lib/python3.9/site-packages/click/decorators.py", line 381, in callback
    raise RuntimeError(
RuntimeError: 'piptools' is not installed. Try passing 'package_name' instead.


```

**Comment by nicoa** [comment] 2021-06-11 16:52
duplicate of https://github.com/jazzband/pip-tools/issues/1398 , this is fixed on main branch and hopefully will be in the next release.

**Closed** 2021-06-11 17:19 UTC
Labels: bug, dependency, duplicate
