### ISSUE TITLE
No handlers could be found for logger "pip.vcs.git"

### ISSUE THREAD

**Issue by cancan101** [jazzband/pip-tools#292] opened 2016-01-14 16:28 UTC
Looks like logging is not totally set up. I get this when `pip-compile` wit VCS links:

```
No handlers could be found for logger "pip.vcs.git"
```

**Comment by ryanhiebert** [comment] 2016-01-30 03:49
FWIW, this issue came up for me about the same time that I added a `-e` requirement to a github repository (starting with `git+git://`).

**Comment by vphilippon** [comment] 2017-11-16 19:09
Has this been since in recent releases?

Note to contributors: Try to reproduce by causing a failure with a git repo on `pip`'s side.

**Comment by ryanhiebert** [comment] 2017-11-16 20:04
I'm still seeing this message each time I run my upgrade script.

**Comment by vphilippon** [comment] 2017-11-16 20:13
@ryanhiebert Could you give me your upgrade script, as well as a `requirements.in` to reproduce?

**Comment by ryanhiebert** [comment] 2017-11-16 20:23
My script is just a thin wrapper, to do some post processing using sed to capitalize some names.

I just ran `pip-compile` on this `requirements.in`:

```
-e git+https://github.com/tim-schilling/django-timezone-field.git@7d6eedee1ce2a1982ef2f32b2f9f1ef9e7e10651#egg=django-timezone-field
```

And it gave me this output:

```
Could not find a tag or branch '7d6eedee1ce2a1982ef2f32b2f9f1ef9e7e10651', assuming commit.
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file requirements.txt requirements.in
#
-e git+https://github.com/tim-schilling/django-timezone-field.git@7d6eedee1ce2a1982ef2f32b2f9f1ef9e7e10651#egg=django-timezone-field
django==1.11.7
pytz==2017.3              # via django
```

**Comment by ryanhiebert** [comment] 2017-11-16 20:23
Sorry, that doesn't have the message. That was dumb.

**Comment by ryanhiebert** [comment] 2017-11-16 20:25
I may have been mis-remembering what I was seeing. I can't confirm the bug myself ATM.

**Comment by vphilippon** [comment] 2017-11-23 19:05
Alright, closing this for now. If anyone comes up with this again, we'll reopen.

**Comment by koleror** [comment] 2018-02-16 15:57
Hi, I add the issue myself running pip-compile with git urls indeed. 
The format of the github urls is: `-e git+ssh://git@github.com/<user>/<repo>.git@<tag>#egg=<egg>`, if it can help?

**Comment by amanagr** [comment] 2018-06-02 10:35
Did anyone figure this out? @cancan101 ??

**Comment by atugushev** [comment] 2019-10-30 07:21
Hello @koleror,

> Hi, I add the issue myself running pip-compile with git urls indeed.
> The format of the github urls is: `-e git+ssh://git@github.com/<user>/<repo>.git@<tag>#egg=<egg>`, if it can help?
> 
> Also, I get `No handlers could be found for logger "pip.req.req_install"`

I cannot reproduce it locally. Is this issue still on, @koleror?

```bash
echo "-e git+ssh://git@github.com/jazzband/pip-tools.git@master#egg=pip-tools" | pip-compile - -vo- > /dev/null
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  pip-tools from git+ssh://****@github.com/jazzband/pip-tools.git@master#egg=pip-tools (from -r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmpflyl5zxs (line 1))

Finding the best candidates:
  found candidate -e git+ssh://git@github.com/jazzband/pip-tools.git@master#egg=pip-tools (constraint was <any>)

Finding secondary dependencies:

New dependencies found in this round:
  adding ['click', '>=6', '[]']
  adding ['six', '', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  click>=6 (from pip-tools->-r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmpflyl5zxs (line 1))
  pip-tools from git+ssh://****@github.com/jazzband/pip-tools.git@master#egg=pip-tools (from -r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmpflyl5zxs (line 1))
  six (from pip-tools->-r /var/folders/4x/rz_w89dx1z3bydfd6qpdjn_h0000gn/T/tmpflyl5zxs (line 1))

Finding the best candidates:
  found candidate click==7.0 (constraint was >=6)
  found candidate -e git+ssh://git@github.com/jazzband/pip-tools.git@master#egg=pip-tools (constraint was <any>)
  found candidate six==1.12.0 (constraint was <any>)

Finding secondary dependencies:
  click==7.0                requires -
  six==1.12.0               requires -
------------------------------------------------------------
Result of round 2: stable, done

#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=- -
#
-e git+ssh://git@github.com/jazzband/pip-tools.git@master#egg=pip-tools
click==7.0
six==1.12.0
```

**Comment by antonagestam** [comment] 2019-11-25 15:58
I am still seeing this with (`pip-compile --version`: `pip-compile, version 4.2.0`)

**Comment by antonagestam** [comment] 2019-11-25 16:00
Actually I am seeing a slightly different error:

```
No handlers could be found for logger "pip._internal.vcs.git"
Traceback (most recent call last):
  File "/Users/anton/.pyenv/versions/dn-campaign/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/scripts/compile.py", line 358, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 168, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 339, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 272, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 231, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 295, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 258, in prepare_editable_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
    command_desc='python setup.py egg_info',
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

And also this:

```
No handlers could be found for logger "pip.subprocessor"
Traceback (most recent call last):
  File "/Users/anton/.pyenv/versions/dn-campaign/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/scripts/compile.py", line 358, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 168, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/resolver.py", line 339, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 272, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/piptools/repositories/pypi.py", line 231, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 295, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 258, in prepare_editable_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
    command_desc='python setup.py egg_info',
  File "/Users/anton/.pyenv/versions/2.7.16/envs/dn-campaign/lib/python2.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by atugushev** [comment] 2019-11-25 16:02
@antonagestam could you paste `requirements.in`? I'll check.

**Comment by palfrey** [comment] 2020-01-18 17:01
I've got the `pip.subprocessor` variant with the following requirements.in

```
Cohen >= 0.7.4

# For https://github.com/lobocv/eventdispatcher/commit/b238ee18fa511c54090c21c7801564edd0dd95ef#diff-3e88a25682c0094a8dfc3cabbaa05dcb to fix clock issue
# The < 1.9.5 is because of https://github.com/lobocv/eventdispatcher/issues/2
eventdispatcher >= 1.9.0,<1.9.5

pip-tools

axiom
tagpy
netifaces
twisted

# Because last release is very broken. See https://github.com/inducer/tagpy/issues/5
-e git+https://github.com/inducer/tagpy.git#egg=tagpy
```

Like the one from https://github.com/palfrey/parochial currently, but with the Twisted version lockdown removed. Incidentally, it works with `twisted < 15` and every value up to `< 19` but not `< 20` so might have something to do with Twisted 19.x?

**Comment by atugushev** [comment] 2020-01-21 18:14
@vphilippon cool! Thanks for the fix!


@antonagestam @palfrey could you please test the #1035 whether it fixes your issue? Coud be installed via:

```console
$ pip install -e 'git+https://github.com/vphilippon/pip-tools.git@configure-builtin-logging-module#egg=pip-tools'
```

**Comment by palfrey** [comment] 2020-01-21 18:22
So it's still not fully working, but we've got a more interesting error message :)
```
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /Users/palfrey/src/parochial/ENV/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/var/folders/hs/z7c0cksd5nz80mjhc2qncx900000gn/T/tmp9IbOujbuild/twisted/setup.py'"'"'; __file__='"'"'/var/folders/hs/z7c0cksd5nz80mjhc2qncx900000gn/T/tmp9IbOujbuild/twisted/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /var/folders/hs/z7c0cksd5nz80mjhc2qncx900000gn/T/tmp9IbOujbuild/twisted/pip-egg-info
     cwd: /var/folders/hs/z7c0cksd5nz80mjhc2qncx900000gn/T/tmp9IbOujbuild/twisted/
Complete output (12 lines):
no previously-included directories found matching '.travis'
no previously-included directories found matching 'tests'
warning: no previously-included files found matching 'examplesetup.py'
no previously-included directories found matching 'src/exampleproj'
no previously-included directories found matching 'src/incremental/newsfragments'

Installed /private/var/folders/hs/z7c0cksd5nz80mjhc2qncx900000gn/T/tmp9IbOujbuild/twisted/.eggs/incremental-17.5.0-py2.7.egg
/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
  warnings.warn(msg)
error in Twisted setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
----------------------------------------
Traceback (most recent call last):
  File "/Users/palfrey/src/parochial/ENV/bin/pip-compile", line 9, in <module>
    load_entry_point('pip-tools==1.10.0rc2.dev488+gcde47c0', 'console_scripts', 'pip-compile')()
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/scripts/compile.py", line 380, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/resolver.py", line 165, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/resolver.py", line 260, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/resolver.py", line 355, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/repositories/local.py", line 70, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/repositories/pypi.py", line 292, in get_dependencies
    download_dir, ireq, wheel_cache
  File "/Users/palfrey/src/parochial/ENV/src/pip-tools/piptools/repositories/pypi.py", line 249, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
    self.metadata_directory = metadata_generator(self)
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
    command_desc='python setup.py egg_info',
  File "/Users/palfrey/src/parochial/ENV/lib/python2.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Note that doing `pip install twisted==19.7.0 --no-binary :all:` (the `--no-binary` is there because the default is a wheel which also works) works fine

**Comment by vphilippon** [comment] 2020-01-21 19:46
@palfrey Alright! My fix was just to fix the logger part, and get a better message, not fix the actual underlying issue it was failing to report :). So this is a good sign.

For this case, with the output, it seems there's something odd with the `twisted` package extras_require. I'd (naively?) expect this to be easily reproducible, but it isn't.
That's a specific issue that we can track with its own ticket. It deserves it :).

A good-ish title to identify it:
"error in Twisted setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers."

**Comment by palfrey** [comment] 2020-01-21 22:55
So, it turns out it's got nothing to do with Twisted at all, but setuptools. My virtualenv had setuptools 18.2 installed, which exhibited this bug, but upgrading to latest (44.0.0) fixed the problem.

**Closed** 2020-01-22 15:02 UTC
Labels: bug, logging
