### ISSUE TITLE
pip-compile fails to override the duplicate package version 

### ISSUE THREAD

**Issue by awais786** [jazzband/pip-tools#1458] opened 2021-07-27 07:10 UTC
Our organisation has 200+ repos,  and it maintained global constraint file which is an online url contains all pins versions like Django<2.3.

In all repos it is defined on top.
-c https://raw.githubusercontent.com/......./common.txt

Now orgnization is shifting to django3.2, but on running upgrade command it fails.
local file has following content. it has 2 entries 
```
-c https://raw.githubusercontent.com/......./common.txt ( it has content django<2.3)
django>2.3,<3.3
````
In this example common file bring django<2.3 but I expect the 2nd entry will get the priority but latest pip fails to resolve the conflict `Could not find a version that matches django<2.3,<3.3,>2.3,`
Previously it was working fine. 

Is there any thing I am missing or its expected behaviour or is there any way to override the local file version or give priority ?

Thanks

**Comment by AndydeCleyre** [comment] 2021-08-11 05:33
If I'm understanding right, this is expected behavior. 

The order of the lines in the input file doesn't matter, and the `-c` should *constrain* and *restrict* any matching packages to the `common.txt` versions, while satisfying the rest of the file. 

And it can't resolve a single `django` version that's both less and more than 2.3.

I'd' probably split into multiple constraints, e.g. `common-django3.txt`, `common-django2.txt`, `common.txt` and start including them in the projects. Or use branches with one `common.txt`.

Alternatively you can use the [version specifier syntax](https://www.python.org/dev/peps/pep-0440/#version-specifiers) to carefully disallow what you don't want globally, but a single version spec might not fit or be sane ultimately.

**Comment by AndydeCleyre** [comment] 2021-09-22 16:19
Hey, it's been a while since any new discussion here.

> Is there any thing I am missing or its expected behaviour or is there any way to override the local file version or give priority ?

AFAIU the behavior is expected: specifying impossible constraints yields an impossible match.

I don't know exactly what behavior you'd want for "overriding," but you could first compile the common constraints to the project's output file, then compile your project's requirements (without setting the common constraints) over that same output file, and I think that might achieve what you're after. You would be losing the guarantees of setting a proper constraints file.

I'm going to close this, but if you want to propose a well defined overriding/prioritizing feature, please do so! I don't think line order will be suitable, since line order doesn't matter to `pip` itself, so it would be unexpected and/or difficult.

**Closed by AndydeCleyre** 2021-09-22 16:19 UTC
