### ISSUE TITLE
Support for default arguments using pyproject.toml

### ISSUE THREAD

**Issue by nikhilweee** [jazzband/pip-tools#1858] opened 2023-04-30 09:41 UTC
#### What's the problem this feature will solve?
Having to specify default arguments to `pip-compile` or `pip-sync`

#### Describe the solution you'd like
Default arguments can be specified in a configuration file, or in a separate section in `pyproject.toml`

I quite like how [pytest uses the `[tools.pytest*]` tables in `pyproject.toml`](https://docs.pytest.org/en/7.3.x/reference/customize.html#pyproject-toml) to get the default arguments.

#### Additional context

Consider a case when I always need the generated `requirements.txt` without any annotations. In this case I will always have to specify `--no-annotations --no-header` as extra command line arguments. If I'm already using `pyproject.toml` to manage my project, I would prefer using the same file to specify the default arguments for `pip-tools`.

**Comment by atugushev** [comment] 2023-04-30 09:43
Duplicate of #604

**Closed by atugushev** 2023-04-30 09:43 UTC
