### ISSUE TITLE
Add a feature to compile platform-agnostic requirements.in (or pyproject.toml) for a specific platform (darwin, windows, linux)

### ISSUE THREAD

**Issue by barseghyanartur** [jazzband/pip-tools#2032] opened 2023-12-12 13:07 UTC
#### What's the problem this feature will solve?

Something similar to poetry currently does, although it doesn't work as I wish it would. There you need to specify the platform inside your requirements in pyproject.toml.

#### Describe the solution you'd like

I prefer to have an platform agnostic requirements that can be compiled for the given platform (``pip-compile --platform=darwin`` ...)

#### Alternative Solutions

There are many paths to go. For instance, one could compile things on GitHub Actions and then generate a PR from it. But doing it differently would be really good.

**Comment by webknjaz** [comment] 2023-12-19 00:36
Duplicate of #826

**Closed by webknjaz** 2023-12-19 00:36 UTC

**Comment by webknjaz** [comment] 2023-12-19 00:38
You may also find the following notes interesting:

- https://github.com/jazzband/pip-tools/issues/1326#issuecomment-1834517252
- https://github.com/jazzband/pip-tools/issues/826#issuecomment-1324127670
