### ISSUE TITLE
-e git+[repo] secondary dependencies are not printed with -v

### ISSUE THREAD

**Issue by Groxx** [jazzband/pip-tools#381] opened 2016-07-20 00:26 UTC
Given a requirements.in file with e.g.:

```
other_dep
tchannel<1,>=0.24
-e git+gitolite@host:/some_package
```

where the some_package git dependency has a requirement on this:

```
tchannel<0.23,>=0.22
```

The pip-compile (1.6.5) output shows like this:

```
Current constraints:
  tchannel<1,>=0.24
  other_dep
  some_package from git+gitolite@host:/some_package

Finding secondary dependencies:
  other_dep requires: ...

New dependencies found in this round:
  adding [stuff other_dep required]
  adding tchannel<1,>=0.24
  adding tchannel<0.23,>=0.22
```

The `-e git+...` dependency's rules are never printed during the "Finding secondary dependencies" step, regardless of what they contain.  This makes it rather hard to find the cause of conflicting requirements :|

---

Interestingly(?), pip 1.7.0 prints the "new dependencies found this round" slightly differently for the `-e` requirements than others:

```
  adding [u'tchannel', "[(u'<', u'1'), (u'>=', u'0.24')]", '[]']
  adding ['tchannel', "[('<', '0.23'), ('>=', '0.22')]", '[]']
```

^ note the non-unicode package name and constraints

**Comment by sbezboro** [comment] 2016-07-20 00:27
👍

**Comment by davidovich** [comment] 2017-03-27 15:03
I think this is a duplicate of #466, let's continue there.

**Closed by davidovich** 2017-03-27 15:03 UTC
