### ISSUE TITLE
pip-compile generate two same dependencies

### ISSUE THREAD

**Issue by Folyd** [jazzband/pip-tools#400] opened 2016-10-15 09:46 UTC
here is what the pip-compile generated file:

```
Flask-Script==2.0.5       # via flask-migrate
Flask-SQLAlchemy==2.1     # via flask-migrate
Flask==0.11.1             # via flask-bcrypt, flask-migrate, flask-script, flask-sqlalchemy,      flask_sqlalchemy
Flask_SQLAlchemy==2.1     # via flask-migrate
```

there are two flask_sqlalchemy statement, and would cause pip install error in gitlab share-runner,
here is the error:
`$ pip install -r requirements/dev.txt
Double requirement given: Flask-SQLAlchemy==2.1 (from -r requirements/prod.txt (line 17)) (already in Flask-SQLAlchemy==2.1 (from -r requirements/prod.txt (line 15)), name='Flask-SQLAlchemy')
`

**Comment by davidovich** [comment] 2016-11-21 18:12
This seems to be a duplicate of #376

**Comment by davidovich** [comment] 2017-02-17 20:57
L'ets close this and continue in #376

**Closed by davidovich** 2017-02-17 20:57 UTC
