### ISSUE TITLE
pip-compile crashes on a setup.py that contains entry_points

### ISSUE THREAD

**Issue by excitedleigh** [jazzband/pip-tools#572] opened 2017-10-03 00:51 UTC
If my setup.py contains `entry_points`, I get an error.

##### Environment Versions

1. OS Type: macOS 10.12.6
1. Python version: `Python 3.6.2`
1. pip version:  `pip 9.0.1`
1. pip-tools version: `pip-compile, version 1.10.1`

##### Steps to replicate

1. Create a new directory
2. Add a setup.py with the following content
3. Run `pip-compile`

```python
from setuptools import find_packages, setup

setup(
    name='myproject',
    description='My awesome project',
    url='https://example.com/',
    author='Adam Brenecki',
    author_email='adam@brenecki.id.au',
    license='Proprietary',
    setup_requires=["setuptools_scm>=1.11.1"],
    use_scm_version=True,
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'dj-database-url',
        'django-csp',
        'django-form-utils',
        'django-redis',
        'django-stronghold',
        'django-widget-tweaks',
        'Django[argon2]',
        'psycopg2',
        'python-decouple',
        'raven',
        'waitress',
        'django-webpack-loader',
    ],
    extras_require={
        'dev': [
            'pre-commit',
            'prospector',
            'pytest',
            'pytest-django',
        ]
    },
    entry_points={
        'console_scripts': ['sl-admin=sl-admin.manage:main'],
    }
)
```

##### Expected result

A `requirements.txt` is produced. This is the result I get with the exact same setup.py but without `entry_points`.

##### Actual result

```
Traceback (most recent call last):
  File "/Users/adam/.pyenv/versions/3.6.2/bin/pip-compile", line 11, in <module>
    sys.exit(cli())
  File "/Users/adam/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adam/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/adam/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adam/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/site-packages/piptools/scripts/compile.py", line 167, in cli
    dist = run_setup(src_file)
  File "/Users/adam/.pyenv/versions/3.6.2/lib/python3.6/distutils/core.py", line 227, in run_setup
    script_name)
RuntimeError: 'distutils.core.setup()' was never called -- perhaps 'setup.py' is not a Distutils setup script?
```

**Comment by vphilippon** [comment] 2017-10-03 13:39
Out of curiosity, could you try this and see if the problem occurs:
`echo "-e ." | pip-compile -o requirements.txt -` (don't forget the `-` at the end, it's required to read from `stdin`)

In short, this will do a `pip-compile` of `-e .` instead of parsing the setup.py directly.
If it works, then the issue is likely with the way we handle the `setup.py` parsing, which is my guess.
It would also possibly give you a workaround until we fix it.

**Comment by abravalheri** [comment] 2018-06-18 23:11
@vphilippon, I was facing the same problem in [this repository](https://github.com/abravalheri/dummy-pipenv-example-for-pyscaffold/tree/pip-tools) (pip-tools branch). Then I added a `requirements.in` file with `-e .` as suggested by you, and things worked fine.

So your guess seem to be consistent...

(thank you very much for the information and workaround!)

**Comment by atugushev** [comment] 2019-09-19 23:14
It looks like `distutils.core.run_setup` fails [silently](https://github.com/python/cpython/blob/v3.7.4/Lib/distutils/core.py#L219-L222), so I've printed the error manually and got this: 

```
 error in myproject setup command: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'sl-admin=sl-admin.manage:main')
```

I've got an error in module path in entry points: change `sl-admin.manage:main` to `sl_admin.manage:main` and it'll work.

**Comment by atugushev** [comment] 2020-02-12 19:57
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!

**Closed by atugushev** 2020-02-12 19:57 UTC
Labels: awaiting response, support
