### ISSUE TITLE
pre-commit does not detect changes in .in files

### ISSUE THREAD

**Issue by MartinThoma** [jazzband/pip-tools#1208] opened 2020-09-02 07:44 UTC
I've added the pre-commit hook so that I cannot forget to compile the .in files to .txt files. It passes, but does not act when it should.

#### Environment Versions

1. OS Type: Ubuntu 20.04
1. Python version: Python 3.8.3
1. pip version:  pip 20.2.2 from /home/moose/.pyenv/versions/3.8.3/lib/python3.8/site-packages/pip (python 3.8)
1. pip-tools version: pip-compile, version 5.3.1

#### Steps to replicate

The pre-commit-config.yaml is:

```
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      - id: pip-compile
        files: ^setup\.py|requirements-dev\.in|requirements-lint\.in$
```

If you want a full example:

```
git clone https://github.com/MartinThoma/HASY.git
cd HASY
sed -i '/flake8-comprehensions/d' requirements-lint.in
pre-commit run --all-files
```

#### Expected result

Updated `requirements-lint.txt`

#### Actual result

No change in `requirements-lint.txt`, but pre-commit passes

**Comment by MartinThoma** [comment] 2020-09-22 21:52
I solved my problem. You might be interested in [check-pip-compile](https://github.com/MartinThoma/check-pip-compile):

```
-   repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.0
    hooks:
    -   id: check-pip-compile
        args: ['.']  # it's recommended to specify the files you want
```

**Comment by atugushev** [comment] 2021-01-05 06:37
Hello @MartinThoma,

Thanks for the issue! You should use a separate hook for each input requirement file, for example:


```yaml
repos:
-   repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        files: ^setup\.py$
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in]
        files: ^requirements-dev\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements-lint.in
        args: [requirements-lint.in]
        files: ^requirements-lint\.(in|txt)$
```

**Comment by atugushev** [comment] 2021-01-30 06:15
I'll close this based on the above comment, but please let us know if it doesn't resolve your issue. Thanks!

**Closed by atugushev** 2021-01-30 06:15 UTC
Labels: pre-commit, support

**Comment by seanytak** [comment] 2021-02-24 01:56
> 
> 
> Hello @MartinThoma,
> 
> Thanks for the issue! You should use a separate hook for each input requirement file, for example:
> 
> ```yaml
> repos:
> -   repo: https://github.com/jazzband/pip-tools
>     rev: 5.3.1
>     hooks:
>       - id: pip-compile
>         name: pip-compile setup.py
>         files: ^setup\.py$
>       - id: pip-compile
>         name: pip-compile requirements-dev.in
>         args: [requirements-dev.in]
>         files: ^requirements-dev\.(in|txt)$
>       - id: pip-compile
>         name: pip-compile requirements-lint.in
>         args: [requirements-lint.in]
>         files: ^requirements-lint\.(in|txt)$
> ```

Would it be possible to add this somewhere in the documentation? I wasn't familiar at all with how pre-commit really worked so it took some digging until I realized that even if the pattern matches for `files` we would still need to feed the names in individually for each requirements file for it to work as intended.

**Comment by atugushev** [comment] 2021-02-24 02:00
> Would it be possible to add this somewhere in the documentation?

@seanytak that's a good idea! Any help with docs is highly welcomed and appreciated 👍🏼

**Comment by atugushev** [comment] 2021-03-01 07:15
@seanytak there is a tracking issue #1335
