### ISSUE TITLE
With pre-releases, pip-compile sometimes adds local version hash, sometimes does not

### ISSUE THREAD

**Issue by tuukkamustonen** [jazzband/pip-tools#785] opened 2019-04-11 14:19 UTC
`pip-compile` sometimes locks to a version with PEP 440 local version identifier, sometimes doesn't.

##### Environment Versions

1. OS Type: linux/KDE Neon (=Ubuntu 18.04 based)
1. Python version: `3.5.5`
1. pip version:  `9.0.1` and `19.0.3`
1. pip-tools version: `3.6.0`

##### Steps to replicate

This happens with package in our company's internal index (devpi), I'm not sure how to reproduce this with a package in PyPI. But maybe someone has similar experiences...

In this example `dep` is dependency for `mypkg`. There are 1.0.0 versions of both, but there's also `1.0.1.dev3` version of `dep` that I would like to test in conjunction.

Prepare:

```shell
$ pyenv virtualenv 3.5.5 foobar
...
$ pyenv activate foobar
...
```

No problem here:

```shell
$ rm -rf ~/.cache/pip-tools/
$ echo "\
dep == 1.0.1.dev3\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.1.dev3
$ echo "\
dep == 1.0.1.dev3\
mypkg == 1.0.0\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.1.dev3
mypkg == 1.0.0
```

So, `dep==1.0.1.dev3` version always when `dep` is first pinned, and `mypkg` is added later.

However, here's the problem:

```shell
$ rm -rf ~/.cache/pip-tools/
$ echo "\
dep == 1.0.1.dev3\
mypkg == 1.0.0\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.1.dev3+gd7cef3b
mypkg == 1.0.0
```

So, in the failure scenario, `dep` gets `+gd7cef3b` local version, when it's in conjunction with `mypkg`.

Though, it also happens when `mypkg` is already resolved and when `dep` is changed to point to pre-release.

```shell
$ rm -rf ~/.cache/pip-tools/
$ echo "\
mypkg == 1.0.0\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.0
mypkg == 1.0.0
$ echo "\
dep == 1.0.1.dev3\
mypkg == 1.0.0\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.1.dev3+gd7cef3b
mypkg == 1.0.0
```

So it fails always when the `mypkg` dependency is present.

The local version is removed if I remove `mypkg` and only directly depend on `dep`:

```shell
$ echo "\
dep == 1.0.1.dev3\
"  > requirements.in
$ pip-compile --no-header --no-index
dep == 1.0.1.dev3
```

This only happens with pre-releases (as actual releases don't have local identifiers). I don't think global PyPI even accepts _local versions_.

**Comment by atugushev** [comment] 2019-04-11 15:19
Hello @tuukkamustonen,

Thank you for the report! Could you upload `mypkg` and `dep` on the [Test PyPI](https://packaging.python.org/guides/using-testpypi/). I mean not your real packages, but test packages like [this one](https://github.com/atugushev/test-package). Could you reproduce the bug on that env?

**Comment by tuukkamustonen** [comment] 2019-04-12 07:15
I will look into it, but I don't have time for that right now. Need to come back to this a bit later.

**Comment by tuukkamustonen** [comment] 2019-10-08 10:43
Still happening in `4.1.0`. I really need to check this.

**Comment by atugushev** [comment] 2020-05-01 14:53
Working on #1114 I've possibly tracked down the issue. `pip` resolver searches all candidates matched to the version, cut down [local version identifier](https://www.python.org/dev/peps/pep-0440/#local-version-identifiers) (e.g., "+gd7cef3")  and get maximum from the list of cut versions, that's why the result is so arbitrary.

Suppose you have the following installation candidates for `foo=1.0.0`:

- foo=1.0.0, url=http://index-url/foo-1.0.0.tar.gz
- foo=1.0.0+dev, url=file:///tmp/path/to/package
- foo=1.0.0+b02632, utl=git@github.com:user/foo.git@02632


`pip` transforms these candidates to install requirements (see https://github.com/jazzband/pip-tools/issues/1114#issuecomment-617167490 for the traceback):

- foo=1.0.0, url=http://index-url/foo-1.0.0.tar.gz
- foo=1.0.0, url=file:///tmp/path/to/package
- foo=1.0.0, utl=git@github.com:user/foo.git@02632

and then gets a package with a max version, thus the result of max() would be arbitrary due to all candidates have the same version.

**Comment by atugushev** [comment] 2020-05-01 14:57
It could be a `pip` bug. I'll try to provide reproducible steps.

**Comment by tuukkamustonen** [comment] 2020-06-29 17:37
Just wanted to update: we recently migrated from `devpi` to [Artifactory](https://jfrog.com/artifactory) and the issue persists. So, I would say it's at least not index-specific.

**Comment by atugushev** [comment] 2022-06-30 09:41
Could you test it with `pip-compile --resolver backtracking`?

**Comment by tuukkamustonen** [comment] 2022-07-04 11:11
Unfortunately, I've switched a new employer and don't have the issue producing code/setup at hand anymore 🤷🏻‍♂️

There seems to be little traffic in this ticket, so you might want to close it and wait for someone else to report the same 🤔

**Comment by atugushev** [comment] 2022-12-14 00:23
I'll close this based on the above. Thanks!

**Closed by atugushev** 2022-12-14 00:23 UTC
Labels: bug, resolver
