### ISSUE TITLE
Is specifying a pip-like constraints file possible?

### ISSUE THREAD

**Issue by cgebbe** [jazzband/pip-tools#1551] opened 2022-01-17 15:25 UTC
#### What's the problem this feature will solve?

- Given a `constraints.txt` file for pypi with the content `GDAL>=1.0`
- and some arbitrary `requirements.in` file without `GDAL`
- and a docker image, where GDAL 1.1 is already installed 
- when we run `pip install`, 
- then pip does not try to install GDAL again

However...,
- ...when we run `pip-compile requirements.in constraints.txt"
- then it tries to install the newest GDAL version (which results in errors due to its special requirements)

Similarly,
- ... when we run `pip-compile requirements.in --pip-args='-c constraints.txt'`
- then it seems that the constraints.txt is simply ignored?

#### Describe the solution you'd like

A pip-like behavior for a constraints.txt file

**Comment by webknjaz** [comment] 2022-01-17 15:30
Make sure to add `-c constraints.txt` _inside_ of `requirements.in`, this is described in the README AFAIR.

**Comment by wbolster** [comment] 2022-02-08 11:06
closing since this seems resolved

**Closed by wbolster** 2022-02-08 11:06 UTC
Labels: question

**Comment by davidxia** [comment] 2022-07-12 20:59
Apparently these options only work if the file is called `requirements.in`. I had the following in my setup.py

```
setup(
    name=NAME,
..
    install_requires=read_requirements("requirements.txt"),
```

and got this error

```
python -m piptools compile
/Users/dxia/.pyenv/versions/skf/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /my-project/setup.py
```

Changing `requirements.txt` to `requirements.in` fixed it.

**Comment by gwerbin** [comment] 2022-09-17 20:07
@webknjaz is it possible to do this when using `pyproject.toml` (entry `project.dependencies`) instead of `requirements.in`? It would be really useful if we could do `pip-tools --constraint constraints.txt pyproject.toml` for example, in the case that `pyproject.toml` deps are a subset of all project deps.

**Comment by AndydeCleyre** [comment] 2022-09-17 20:11
A simple way to achieve that is to use a higher-level `.in` file, e.g.:

`project-requirements.in`:
```ini
-e .
-c constraints.txt
```

**Comment by gwerbin** [comment] 2022-09-18 03:05
@AndydeCleyre that's clever, thanks!

**Comment by gwerbin** [comment] 2022-11-16 06:40
@AndydeCleyre I've spent some time using this technique, and it introduces a bit of a problem.

I was hoping to implement a workflow like this:

1. Generate `constraints.txt` using `requirements.in` and `requirements-dev.in`
2. Generate `requirements.txt` from `requirements.in` and `constraints.txt`.
3. Generate `requirements-dev.txt` from `requirements.in`, `requirements-dev.in`, and `constraints.txt`.
4. Install `requirements.txt` in "prod" environments. Install `requirements-dev.txt` in "dev" environments.

This seems to be the only way to ensure that "prod" and "dev" have the exact same versions of all dependencies.

The problem is that, without a way to explicitly specify a constraints file when running `pip-compile`, this introduces a circular dependency! You need `requirements*.in` to generate `constraints.txt`, but you need to refer to `constraints.txt` inside `requirements*.in` in order to get `pip-compile` to recognize the constraints file!

My workaround was to temporarily generate a `requirements.tmp` file with the `-c constraints.txt` line inserted at the top, and use _that_ to generate `requirements.txt`. However that's quite ugly and requires nontrivial scripting, Makefile usage, etc.

It would be really useful if `pip-compile` had a `--constraint` option for this purpose.

**Comment by AndydeCleyre** [comment] 2022-11-16 16:16
> 1\. Generate constraints.txt using requirements.in and requirements-dev.in

`constraints.in`:
```ini
-r requirements.in
-r requirements-dev.in
```
```console
$ pip-compile --strip-extras constraints.in
```

> 2\. Generate requirements.txt from requirements.in and constraints.txt.

`requirements-constrained.in`:
```ini
-r requirements.in
-c constraints.txt
```
```console
$ pip-compile requirements-constrained.in -o requirements.txt
```

> 3\. Generate requirements-dev.txt from requirements.in, requirements-dev.in, and constraints.txt.

`requirements-dev-constrained.in`:
```ini
-r requirements.in
-r requirements-dev.in
-c constraints.txt
```
```console
$ pip-compile requirements-dev-constrained.in -o requirements-dev.txt
```

**Comment by gwerbin** [comment] 2022-11-16 16:46
@AndydeCleyre the need for those `requirements*-constrained.txt` files are exactly the problem that was describing above. They are awkward and make for a somewhat confusing pile of "intermediate" config files in the project.

If `pip-tools` itself had the ability to  recognize constraints and requirements files separately, you wouldn't need them.

**Comment by AndydeCleyre** [comment] 2022-11-16 16:49
This is probably just a typo, but to be clear, the above-posted solution does *not* include any `requirements*-constrained.txt` files (just `.in` files).

**Comment by gwerbin** [comment] 2022-11-16 16:54
> This is probably just a typo, but to be clear, the above-posted solution does _not_ include any `requirements*-constrained.txt` files (just `.in` files).

Yes, that was my mistake. I meant `.in`, not `.txt`.

**Comment by AndydeCleyre** [comment] 2022-11-26 17:36
I want to say that despite my posting alternatives here, I am not against reopening this.

Here's another workaround to pass a constraints file on a Zsh command line, by passing each line from it as an argument to `-P`/`--upgrade-package`:

```bash
constraints=(${(f)"$(<constraints.txt)"}); pip-compile ${${constraints/*/-P}:^constraints} reqs.in
```
