### ISSUE TITLE
Hash problem between PyPi and piwheels?!?

### ISSUE THREAD

**Issue by jedie** [jazzband/pip-tools#1734] opened 2022-11-19 20:02 UTC
Seems that there are problem with not matching package hashes if `pip-compile` runs on a normal PC with **PyPi** repository and then try to install the freezes packages on a **Raspberry Pi** where https://www.piwheels.org/ is used.

Looks like:

![grafik](https://user-images.githubusercontent.com/71315/202869267-e3051cee-a7b5-46c3-99fe-42c0697247ba.png)

or

![grafik](https://user-images.githubusercontent.com/71315/202869280-3dcc8bb6-843a-4c27-bfa0-c787f6b1c984.png)

**Comment by atugushev** [comment] 2022-11-20 01:01
Duplicate of #1536.

**Closed by atugushev** 2022-11-20 01:01 UTC
