### ISSUE TITLE
Log errors for incorrect pyproject.toml

### ISSUE THREAD

**Issue by nikhilweee** [jazzband/pip-tools#1860] opened 2023-05-04 05:11 UTC
My Problem
---

I'm using pip-tools to manage the requirements of a project that I don't indend to distribute. My `pyproject.toml` looks like this.

```toml
# pyproject.toml
[project]
name = "name"
version = "1.0"
dependencies = ["name==1.0"]
```

When I try to run `pip-compile`, I get a very unhelpful error.

```
$ pip-compile pyproject.toml
Backend subprocess exited when trying to invoke get_requires_for_build_wheel
Failed to parse /path/to/pyproject.toml
```

To add to my problems, `validate-pyproject` does not discover any errors either

```
$ validate-pyproject pyproject.toml
Valid file: pyproject.toml
```

The Solution
---

In my particular case, the solution was to add the following section to `pyproject.toml`

```
[tool.setuptools]
py-modules = []
```

I was able to figure this out by changing the following line to remove the `stderr` argument.
```python
# file: site-packages/pyproject_hooks/_impl.py
...
def quiet_subprocess_runner(...):
    ...
    check_output(cmd, cwd=cwd, env=env, stderr=STDOUT)
```

Once I do that, I can run `pip-compile` and immediately find the error:

```
error: Multiple top-level packages discovered in a flat-layout: ['static', 'project', 'app'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.
```

Future Work
---

I don't think we should deprive users of such a helpful message.

Right now the `build` library defaults to using a `quiet` subprocess runner. In a future release, `build` will allow the option to specify the runner explicitly (https://github.com/pypa/build/pull/566). When the next version of `build` is released, we should consider changing the following lines to use `pyproject_hooks.default_subprocess_runner` so that errors are also printed to the terminal.

https://github.com/jazzband/pip-tools/blob/0d2d1f2fbf6b4f59f52561b262e04f9fe4550e3b/piptools/scripts/compile.py#L496-L499

**Comment by nikhilweee** [comment] 2023-05-04 05:23
Turns out this is being actively tracked in #1711 . For those who stumble upon this issue, an easier way to see the error message is to simply try `pip install .` or `python -m build` as described in https://github.com/jazzband/pip-tools/issues/1711#issuecomment-1302504460

**Comment by nikhilweee** [comment] 2023-05-04 05:25
Fun fact: https://github.com/pypa/build/pull/566 was a result of https://github.com/pypa/build/issues/553 which originated out of #1711 so we've come a full circle here.

**Comment by atugushev** [comment] 2023-05-04 09:43
I'll close this as duplicate of #1711. Nonetheless, thanks for the issue!

**Closed by atugushev** 2023-05-04 09:43 UTC
