### ISSUE TITLE
'-e .' resolves to absolute path, breaking compatibility 

### ISSUE THREAD

**Issue by rpkilby** [jazzband/pip-tools#663] opened 2018-05-24 04:14 UTC
`-e .` resolves to an absolute path on the local machine, breaking the `requirements.txt` file for other users since they most likely don't have the package source installed at the same path. Luckily, it's not too difficult to keep up with the output, although it is annoying.

##### Environment Versions

1. OS Type: `macOS`
1. Python version: `3.6.0`
1. pip version:  `10.0.1`
1. pip-tools version: `2.0.2`

##### Steps to replicate

1. Add package to `requirements.in` as `-e .[extradep]`
2. `pip-compile --output-file requirements.txt requirements.in`

##### Expected result

- `requirements.txt` contains `-e .`
- `requirements.txt` contains resolved extra dependencies

##### Actual result

- `requirements.txt` contains `-e file:///absolute/path/to/package/on/local/machine`
- `requirements.txt` contains resolved extra dependencies

**Comment by strichter** [comment] 2018-05-30 08:08
In my case the extra deps are not added to `requirements.txt`.

**Comment by rpkilby** [comment] 2018-05-30 14:57
Hi @strichter - you're looking for #625

**Comment by regisb** [comment] 2018-07-06 11:37
I observe the same behaviour, even though the local project does not have extra dependencies. This is annoying because it forces us to manually run `pip install -e .` after every `pip-sync`.
This issue seems to be related to PR #507.

**Comment by mm-matthias** [comment] 2018-10-31 15:32
Duplicate of #204

**Comment by atugushev** [comment] 2019-09-19 22:20
Let's track it in #204.

**Closed by atugushev** 2019-09-19 22:20 UTC
