### ISSUE TITLE
Multi-architecture hash support

### ISSUE THREAD

**Issue by laurentsimon** [jazzband/pip-tools#2050] opened 2024-01-23 19:00 UTC
#### What's the problem this feature will solve?

I have a project with ~1000 lines of pure python. I would like to generate a requirements.txt with hashes (`--generate-hashes`) that is platform-agnostic, ie I don't want to have to maintain multiple requirements.txt for each OS / architecture.

Some of my dependencies have architecture-specific wheels (i86, x64, osx, Windows, etc), and `pip-compile` produces hashes for platform-specific wheels. So I need to maintain a combination of requirements.txt, which is _really_ hard.

#### Describe the solution you'd like

I would like the pip-compile command to generate a hash that refers to some sort of "bundle / manifest of hashes". This way the requirements.txt becomes platform-agnostic. I understand that pip won't understand this "bundle / manifest", so I probably need to ask on the pip repo as well? 

Note: In docker containers, there is a similar option. As a user you can refer to a multi-arch image by hash, and docker will automatically pick the right image within the bundle to install on your machine

**Comment by laurentsimon** [comment] 2024-01-23 19:00
@di

**Comment by webknjaz** [comment] 2024-01-24 13:08
Duplicate of #826

**Comment by webknjaz** [comment] 2024-01-24 13:09
Also, this isn't realistic at the moment: https://github.com/jazzband/pip-tools/issues/1326#issuecomment-1834517252.

**Closed by webknjaz** 2024-01-24 13:08 UTC
