### ISSUE TITLE
pip-compile fails with version settings in setup.cfg

### ISSUE THREAD

**Issue by Thomasillo** [jazzband/pip-tools#1535] opened 2021-11-12 09:42 UTC
#### Environment Versions

1. OS Type Windows10
1. Python version: 3.7.12
1. pip version: 21.3.1
1. pip-tools version: 6.4.0

#### Steps to replicate

1.
```
# setup.cfg
[metadata]
name=Thing
version = attr: Thing.__version__
[options]
install_requires = 
    requests
```

```
#setup.py
import setuptools
setuptools.setup()
```

```
# Thing/__init__.py
__version__ = "1.0.0"
```

Then run 
```
$ pip-compile
Traceback (most recent call last):
  File "/home/tisele/.local/miniconda3/envs/TEST/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/piptools/scripts/compile.py", line 408, in cli
    dist = meta.load(os.path.dirname(os.path.abspath(src_file)))
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/meta.py", line 71, in load
    path = Path(build_as_zip(builder))
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/meta.py", line 58, in build_as_zip
    builder(dest=out_dir)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/meta.py", line 53, in build
    _prep_meta(hooks, env, dest)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/meta.py", line 28, in _prep_meta
    reqs = hooks.get_requires_for_build_wheel({})
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/wrappers.py", line 173, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/wrappers.py", line 325, in _call_hook
    extra_environ=extra_environ
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/wrappers.py", line 75, in quiet_subprocess_runner
    check_output(cmd, cwd=cwd, env=env, stderr=STDOUT)
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/tisele/.local/miniconda3/envs/TEST/bin/python3.7', '/home/tisele/.local/miniconda3/envs/TEST/lib/python3.7/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_wheel', '/tmp/tmpuaxtfj91']' returned non-zero exit status 1.
```

Without the line 
`version = attr: Thing.__version__` it works.

#### Expected result
No error, a valid requirements.txt file

**Comment by atugushev** [comment] 2021-11-12 11:18
Could you try `pip install -e .`?

**Comment by Thomasillo** [comment] 2021-11-12 13:00
That seems to work.

**Comment by averms** [comment] 2021-11-30 23:32
I'm also using setup.cfg in my projects but I can't reproduce this. I tried to make something exactly like your project. This is the tree output:

```
$ tree -L 2
.
├── python_packages
│   ├── bin
│   ├── lib
│   └── pyvenv.cfg
├── setup.cfg
├── setup.py
└── Thing
    └── __init__.py

4 directories, 4 files
```

I'm using Python 3.9 with the following packages:

```
Package    Version
---------- -------
click      8.0.3
pep517     0.12.0
pip        21.3.1
pip-tools  6.4.0
setuptools 59.2.0
tomli      1.2.2
wheel      0.37.0
```

**Comment by AndydeCleyre** [comment] 2022-03-30 15:45
@Thomasillo 

Hello! It's been a while since you first encountered this. Are you still able to reproduce the problem?

If not, it may be time to close this one.

Thanks!

**Comment by AndydeCleyre** [comment] 2022-05-25 20:15
@Thomasillo 

Please comment here with an update if you can still reproduce this, and I'll re-open, but for now I'm going to close this.

Thanks!

**Closed by AndydeCleyre** 2022-05-25 20:15 UTC
Labels: needs reproduce
