### ISSUE TITLE
more helpful output if impossible dependencies are given

### ISSUE THREAD

**Issue by stefanfoulis** [jazzband/pip-tools#220] opened 2015-10-23 08:39 UTC
The output you get when there are impossible dependencies is not very helpful to debug what package is at fault. Currently it is necessary to look at the `setup.py` of every package involved to find the problem.

The current output is something like this:

```
Could not find a version that matches django-cms<3.1,<3.2,==3.1.3,>=3.0,>=3.0.12
Tried: 2.0.1, 2.0.2, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2, 2.2.1, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.1.0b1, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3
```

It would be really useful if the output could be something like this:

```
Could not find a version that matches django-cms<3.1,<3.2,==3.1.3,>=3.0,>=3.0.12
Tried: 2.0.1, 2.0.2, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2, 2.2.1, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 3.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.0.8, 3.0.9, 3.0.10, 3.0.11, 3.0.12, 3.0.13, 3.0.14, 3.0.15, 3.1.0b1, 3.1.0rc1, 3.1.0rc2, 3.1.0, 3.1.1, 3.1.2, 3.1.3

django-cms dependencies:

django-whatever==1.2  requires >3.1
django-somethingelse==0.5  requires ==3.1.3
django-anotherone==1.2  requires >=3.0
...
```

**Comment by quinox** [comment] 2015-12-28 10:51
I agree.

In the meantime you can get the same information by running it as:
 `pip-compile --verbose | grep ' requires .* django-cms'`

**Comment by tysonclugg** [comment] 2018-05-02 12:04
Duplicate of #165.

**Closed** 2018-05-02 12:04 UTC
Labels: PR wanted
