### ISSUE TITLE
Feature request: put sub-dependencies first, in pip-compile output

### ISSUE THREAD

**Issue by kengruven** [jazzband/pip-tools#312] opened 2016-02-02 16:00 UTC
(This request is based on my assumption that "pip -r req.txt" works by installing the first line of req.txt, then the second, and so on, with no global version resolution first.  If my reading of the Pip documentation is wrong, then this feature request is mistaken, and this is actually a Pip bug.)

Here's something I ran into today.  I want to install Pyramid 1.6.0, so I have a requirements.in file that has:

```
pyramid==1.6.0
```

Pyramid depends on WebOb>=1.3.1.  There's a WebOb==1.5.1, and very recently, a WebOb==1.6.0a.  The alpha doesn't seem to install for me.  That should be no big deal, because I pin exact versions, and everything I use claims to be happy with 1.5.1.

So I put in my requirements.in file:

```
pyramid==1.6.0
WebOb==1.5.1
```

and then I run `pip-compile` on it, and I get a requirements.txt file that looks structurally like:

```
pyramid==1.6.0
WebOb==1.5.1
```

When I run `pip install -r requirements.txt` on this, it first starts to install Pyramid, which asks for WebOb>=1.3.1, so it tries to install WebOb 1.6.0a, and then later tries to uninstall it and then install WebOb 1.5.1.  Somewhere in this process, it fails.  Even if it succeeded, it would be inefficient.

It would be great if pip-compile put the lowest-level dependencies first, like so:

```
WebOb==1.5.1
pyramid==1.6.0
```

so that if I pinned a lower version of a dependency, then it wouldn't bother with the newer version at all.

**Comment by davidovich** [comment] 2017-02-19 15:50
Pip (which does the heavy lifting for pip-tools) should already take care of installing sub dependencies first: see [pip installation order](https://pip.pypa.io/en/stable/reference/pip_install/#installation-order).

Is this issue still relevant with a more modern pip ?

**Comment by kengruven** [comment] 2017-02-20 02:16
I don't know, and I'm not even using Python any more.  Feel free to close this issue, if nobody can reproduce it.

**Comment by davidovich** [comment] 2017-02-20 03:52
Thank you. Closing, by assuming that the issue is resolved by the pip sub-dependency management change.

**Closed by davidovich** 2017-02-20 03:52 UTC
