### ISSUE TITLE
Question regarding workflow to add a package to a .in file

### ISSUE THREAD

**Issue by tmzhuang** [jazzband/pip-tools#847] opened 2019-07-14 04:23 UTC
I'm wondering what the canonical way to add a requirement to a .in file is.

For example:

base.in:
-e ./packageA

base.txt:
req1==0.1 # via packageA
req2==0.1 # via packageA

Now I want to add packageB  to base.in:
base.in:
-e ./packageA
-e ./packageB

I want the requirements of packageB to show up in base.txt, but not upgrade anything in base.txt without explicitly updating. I notice that if I do a pip-compile on base.in here, some packages get updated:
base.txt:
req1==0.2 # via packageA <-- what's the right way to prevent this from happening
req2==0.1 # via packageA, packageB
req3==0.1 # via packageA

**Comment by ulgens** [comment] 2019-07-14 16:37
This means dependencies of packageA was outdated in your requirements.txt file and they needs to be updated before you add something else. What you are trying to achieve doesn't sound like a healthy approach, and i don't think there is a reasonable way to do that, except editing the output file manually.

**Comment by tmzhuang** [comment] 2019-07-14 17:08
@ulgens Can you elaborate more on what you mean by "the dependencies of packageA" was outdated? I'm simply trying to limit the variance in my environment. In this case, I'm in full control of both packageA and packageB since they are local packages. The dependencies are pulled from the setup.py of the packages. Should I be pinning versions in my setup.py?

**Comment by atugushev** [comment] 2019-07-16 15:14
Hello @tmzhuang,

I'm glad you asked. You should just add a package to `base.in` and run `pip-compile base.in`, since pip-compile doesn't upgrade any other packages packages presented in `base.txt` unless you told so via `--upgrade` or `--upgrade-package` options.

For example:
```bash
$ cat requirements.in
pytz

$ pip-compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
pytz==2018.9   # <----------- old version

$ echo six >> requirements.in
$ cat requirements.in
pytz
six

$ pip-compile
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
pytz==2018.9   # <----------- still same old version
six==1.12.0

$ pip-compile --upgrade
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
pytz==2019.1   # <----------- now it's upgraded to a new version
six==1.12.0

```

**Comment by cacarrara** [comment] 2019-08-03 11:53
@tmzhuang 

Couldn't you just pin the `PackageA` version on `base.in` file?

However if your generated `base.txt` file has the same version for `PackageA` but its requirements are being changed, so it can be an indicator that you have an issue with your hypothetical `PackageA` updating its dependencies for a specific version.

**Comment by AndydeCleyre** [comment] 2019-12-31 22:42
@tmzhuang Can you provide a reproducible example? As far as I understand, the behavior you want is the behavior we already have.

**Comment by AndydeCleyre** [comment] 2020-03-10 23:07
Move to close as invalid, as requested behavior == actual behavior, and OP hasn't participated 8 months.

**Comment by atugushev** [comment] 2020-03-11 06:31
I'll close this based on the above, but please let us know if it doesn't resolve your issue. Thanks!

**Closed by atugushev** 2020-03-11 06:31 UTC
Labels: awaiting response, question
