### ISSUE TITLE
pip-compile detects two different versions of same package

### ISSUE THREAD

**Issue by mosesontheweb** [jazzband/pip-tools#1226] opened 2020-11-16 18:36 UTC
#### Environment Versions

1. OS Type: **Linux (Ubuntu 20.04)**
1. Python version: `$ python -V` **3.8.5**
1. pip version:  `$ pip --version` **20.2.4**
1. pip-tools version: `$ pip-compile --version` **5.3.1**

#### Steps to replicate

1. Create two files, one is `dev-requirements.in` and second is `setup.cfg/.py`
2. In `dev-requirements.in` note down `pytest`
3. In `setup.cfg/.py` add `attrs` in section `[install_requires]`
4. enter `pip-compile` and `pip-compile dev-requirements.in`

#### Expected result
From my point of view both `requirements.txt` and `dev-requirements.txt` should have `attrs==20.3.0`

#### Actual result
Both files have different constraint numbers for `attrs`. While `requirements.txt` has 20.3.0, `dev-requirements.txt` has 20.2.0, even though that there's no real constraint set. My setup.cfg just requires attrs, pytest 6.1.1 requires `attrs>=17.4.0`, so 20.3.0 should be the result for both files. No other package requires `attrs`.
Even though adding `attrs` explicitly in `dev-requirements.in` pip-compile detects version 20.2.0 as the best candidate.

**Comment by atugushev** [comment] 2020-12-04 17:39
Hello @mosesontheweb,

Thanks for the issue! It looks like you might have compiled `requirements.txt` and `dev-requirements.txt` at a different times, which is why `attrs` was pinned differently. Could you try `-U` option? For example:

```
$ pip-compile -U
$ pip-compile dev-requirements.in -U
```

**Comment by AndydeCleyre** [comment] 2021-09-25 06:02
I think the issue is properly addressed above, so I'm going to close this, but please write back if it's not quite resolved. 

Thanks!

**Closed by AndydeCleyre** 2021-09-25 06:02 UTC
Labels: support, awaiting response
