### ISSUE TITLE
Alembic 1.4.2 breaks pip-compile 5.2.1

### ISSUE THREAD

**Issue by MartinThoma** [jazzband/pip-tools#1171] opened 2020-07-03 05:47 UTC
#### Environment Versions

1. OS Type: Ubuntu
1. Python version: `Python 3.8.1`
1. pip version:  `pip 20.1.1 from /home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip (python 3.8)`
1. pip-tools version: `pip-compile, version 5.2.1`

#### Steps to replicate

1. `pip install pip-tools==5.2.1`
2. Create an empty directory, put a `requirements.in` with `alembic==1.4.2` as the only content in it
3. Switch in that directory and execute `pip-compile` 

#### Expected result

With `alembic==1.4.1` I get the following requirements.txt. I expected something similar:

```
#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
alembic==1.4.1            # via -r requirements.in
mako==1.1.3               # via alembic
markupsafe==1.1.1         # via mako
python-dateutil==2.8.1    # via alembic
python-editor==1.0.4      # via alembic
six==1.15.0               # via python-dateutil
sqlalchemy==1.3.18        # via alembic
```

#### Actual result

```
$ pip-compile
    ERROR: Command errored out with exit status 1:
     command: /home/math/.pyenv/versions/3.8.1/bin/python3.8 /home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-27xtrkc1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
         cwd: None
    Complete output (44 lines):
    Traceback (most recent call last):
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 193, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/__main__.py", line 26, in <module>
        sys.exit(_main())
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
        command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
        module = importlib.import_module(module_path)
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
        from pip._internal.cli.req_command import RequirementCommand, with_cleanup
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
        from pip._internal.index.package_finder import PackageFinder
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
        from pip._internal.index.collector import parse_links
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
        from pip._vendor import html5lib, requests
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
        from . import utils
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
        from . import certs
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
        from pip._vendor.certifi import where
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
        from .core import contents, where
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
        from importlib.resources import read_text
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/importlib/resources.py", line 11, in <module>
        from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/typing.py", line 1357, in <module>
        class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
      File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/typing.py", line 1005, in __new__
        self._abc_registry = extra._abc_registry
    AttributeError: type object 'Callable' has no attribute '_abc_registry'
    ----------------------------------------
Traceback (most recent call last):
  File "/home/math/.pyenv/versions/3.8.1/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/home/math/.local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/math/.local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/math/.local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/math/.local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/math/.local/lib/python3.8/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/scripts/compile.py", line 444, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/resolver.py", line 169, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/resolver.py", line 274, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/resolver.py", line 380, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/repositories/local.py", line 74, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 228, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/piptools/repositories/pypi.py", line 181, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 362, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 314, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/build_env.py", line 199, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 241, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/math/.pyenv/versions/3.8.1/bin/python3.8 /home/math/.pyenv/versions/3.8.1/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-27xtrkc1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

**Comment by atugushev** [comment] 2020-07-03 09:29
Hello @MartinThoma,

Thanks for the issue! Possible related to https://github.com/pypa/pip/issues/8272.

**Comment by atugushev** [comment] 2020-08-01 03:43
@MartinThoma 

Can't reproduce this bug.

<details>

<summary>See details</summary>

```console

user@host:~$ docker run --rm -it python:3.8 bash

root@c775c83ce43b:/# uname -a
Linux c775c83ce43b 5.3.0-1034-azure #35~18.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020 x86_64 GNU/Linux

root@c775c83ce43b:/# pip --version
pip 20.1.1 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)

root@c775c83ce43b:/# pip-compile --version
pip-compile, version 5.2.1

root@c775c83ce43b:/# cat requirements.in
alembic==1.4.2

root@c775c83ce43b:/# pip-compile -v
Using indexes:
  https://pypi.org/simple

                          ROUND 1
Current constraints:
  alembic==1.4.2 (from -r requirements.in (line 1))

Finding the best candidates:
  found candidate alembic==1.4.2 (constraint was ==1.4.2)

Finding secondary dependencies:
  alembic==1.4.2 not in cache, need to check index
  Collecting alembic==1.4.2
    Downloading alembic-1.4.2.tar.gz (1.1 MB)
       |████████████████████████████████| 1.1 MB 9.2 MB/s
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
      Preparing wheel metadata ... done
    Saved /root/.cache/pip-tools/pkgs/alembic-1.4.2.tar.gz
  alembic==1.4.2            requires Mako, python-dateutil, python-editor>=0.3, SQLAlchemy>=1.1.0

New dependencies found in this round:
  adding ['mako', '', '[]']
  adding ['python-dateutil', '', '[]']
  adding ['python-editor', '>=0.3', '[]']
  adding ['sqlalchemy', '>=1.1.0', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 1: not stable

                          ROUND 2
Current constraints:
  alembic==1.4.2 from https://files.pythonhosted.org/packages/60/1e/cabc75a189de0fbb2841d0975243e59bde8b7822bacbb95008ac6fe9ad47/alembic-1.4.2.tar.gz#sha256=035ab00497217628bf5d0be82d664d8713ab13d37b630084da8e1f98facf4dbf (from -r requirements.in (line 1))
  Mako (from alembic==1.4.2->-r requirements.in (line 1))
  python-dateutil (from alembic==1.4.2->-r requirements.in (line 1))
  python-editor>=0.3 (from alembic==1.4.2->-r requirements.in (line 1))
  SQLAlchemy>=1.1.0 (from alembic==1.4.2->-r requirements.in (line 1))

Finding the best candidates:
  found candidate alembic==1.4.2 (constraint was ==1.4.2)
  found candidate mako==1.1.3 (constraint was <any>)
  found candidate python-dateutil==2.8.1 (constraint was <any>)
  found candidate python-editor==1.0.4 (constraint was >=0.3)
  found candidate sqlalchemy==1.3.18 (constraint was >=1.1.0)

Finding secondary dependencies:
  python-editor==1.0.4 not in cache, need to check index
  Collecting python-editor==1.0.4
    Downloading python_editor-1.0.4-py3-none-any.whl (4.9 kB)
    Saved /root/.cache/pip-tools/wheels/python_editor-1.0.4-py3-none-any.whl
  python-editor==1.0.4      requires -
  mako==1.1.3 not in cache, need to check index
  Collecting Mako==1.1.3
    Downloading Mako-1.1.3-py2.py3-none-any.whl (75 kB)
       |████████████████████████████████| 75 kB 1.3 MB/s
    Saved /root/.cache/pip-tools/wheels/Mako-1.1.3-py2.py3-none-any.whl
  mako==1.1.3               requires MarkupSafe>=0.9.2
  sqlalchemy==1.3.18 not in cache, need to check index
  Collecting SQLAlchemy==1.3.18
    Downloading SQLAlchemy-1.3.18-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
       |████████████████████████████████| 1.3 MB 50.0 MB/s
    Saved /root/.cache/pip-tools/wheels/SQLAlchemy-1.3.18-cp38-cp38-manylinux2010_x86_64.whl
  sqlalchemy==1.3.18        requires -
  alembic==1.4.2            requires Mako, python-dateutil, python-editor>=0.3, SQLAlchemy>=1.1.0
  python-dateutil==2.8.1 not in cache, need to check index
  Collecting python-dateutil==2.8.1
    Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
       |████████████████████████████████| 227 kB 74.3 MB/s
    Saved /root/.cache/pip-tools/wheels/python_dateutil-2.8.1-py2.py3-none-any.whl
  python-dateutil==2.8.1    requires six>=1.5

New dependencies found in this round:
  adding ['markupsafe', '>=0.9.2', '[]']
  adding ['six', '>=1.5', '[]']
Removed dependencies in this round:
------------------------------------------------------------
Result of round 2: not stable

                          ROUND 3
Current constraints:
  alembic==1.4.2 from https://files.pythonhosted.org/packages/60/1e/cabc75a189de0fbb2841d0975243e59bde8b7822bacbb95008ac6fe9ad47/alembic-1.4.2.tar.gz#sha256=035ab00497217628bf5d0be82d664d8713ab13d37b630084da8e1f98facf4dbf (from -r requirements.in (line 1))
  Mako (from alembic==1.4.2->-r requirements.in (line 1))
  MarkupSafe>=0.9.2 (from Mako==1.1.3->alembic==1.4.2->-r requirements.in (line 1))
  python-dateutil (from alembic==1.4.2->-r requirements.in (line 1))
  python-editor>=0.3 (from alembic==1.4.2->-r requirements.in (line 1))
  six>=1.5 (from python-dateutil==2.8.1->alembic==1.4.2->-r requirements.in (line 1))
  SQLAlchemy>=1.1.0 (from alembic==1.4.2->-r requirements.in (line 1))

Finding the best candidates:
  found candidate alembic==1.4.2 (constraint was ==1.4.2)
  found candidate mako==1.1.3 (constraint was <any>)
  found candidate markupsafe==1.1.1 (constraint was >=0.9.2)
  found candidate python-dateutil==2.8.1 (constraint was <any>)
  found candidate python-editor==1.0.4 (constraint was >=0.3)
  found candidate six==1.15.0 (constraint was >=1.5)
  found candidate sqlalchemy==1.3.18 (constraint was >=1.1.0)

Finding secondary dependencies:
  markupsafe==1.1.1 not in cache, need to check index
  Collecting MarkupSafe==1.1.1
    Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
    Saved /root/.cache/pip-tools/wheels/MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl
  markupsafe==1.1.1         requires -
  mako==1.1.3               requires MarkupSafe>=0.9.2
  sqlalchemy==1.3.18        requires -
  alembic==1.4.2            requires Mako, python-dateutil, python-editor>=0.3, SQLAlchemy>=1.1.0
  python-editor==1.0.4      requires -
  python-dateutil==2.8.1    requires six>=1.5
  six==1.15.0 not in cache, need to check index
  Collecting six==1.15.0
    Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
    Saved /root/.cache/pip-tools/wheels/six-1.15.0-py2.py3-none-any.whl
  six==1.15.0               requires -
------------------------------------------------------------
Result of round 3: stable, done

#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile
#
alembic==1.4.2            # via -r requirements.in
mako==1.1.3               # via alembic
markupsafe==1.1.1         # via mako
python-dateutil==2.8.1    # via alembic
python-editor==1.0.4      # via alembic
six==1.15.0               # via python-dateutil
sqlalchemy==1.3.18        # via alembic
```

</details>

**Comment by MartinThoma** [comment] 2020-08-01 20:52
I only vaguely remember this one. I think it was related to https://github.com/pypa/pip/issues/7874 ? (I cannot reproduce this bug anymore as I have no longer access to the codebase where it happened)

**Comment by MartinThoma** [comment] 2020-08-01 20:56
I suggest to close it until somebody can reproduce it. Would that be fine?

**Comment by atugushev** [comment] 2020-08-02 02:36
I'll close this then. Thanks!

**Closed by atugushev** 2020-08-02 02:36 UTC
Labels: awaiting response, bug, needs reproduce
