### ISSUE TITLE
Windows scripts not available

### ISSUE THREAD

**Issue by MinchinWeb** [jazzband/pip-tools#121] opened 2014-11-19 22:11 UTC
When installed in Windows, the scripts are not available from the command line.

**Comment by jmozmoz** [comment] 2015-04-08 19:34
If I call the pip-review script directly the first character is missing:
```
c:\opt\Python34>python Scripts\pip-review
)artopy==0.12.0rc1 is available (you have 0.11.x
)ython==0.22 is available (you have 0.20.2
```
(the packages are cartopy and cython)

**Comment by jgonggrijp** [comment] 2016-12-15 22:57
For the new standalone pip-review, this (i.e. the unavailability of the script under Windows) was fixed in [version 0.5](https://pypi.python.org/pypi/pip-review/0.5). If this is still an issue with the current pip-compile and pip-sync, I suggest having a look at https://github.com/jgonggrijp/pip-review/commit/a08ee67c7e5c670267f90f7b992ede2107a9cde8 for a clean way to tackle this. See also https://github.com/jgonggrijp/pip-review/issues/12.

As for the unrelated issue reported by @jmozmoz, this is a duplicate of https://github.com/nvie/pip-tools/issues/182, https://github.com/jgonggrijp/pip-review/issues/14 and https://github.com/jgonggrijp/pip-review/issues/17. It was fixed in https://github.com/jgonggrijp/pip-review/pull/16. I plan to publish a new version to PyPI that includes the fix soon.

**Comment by davidovich** [comment] 2017-02-17 21:08
This issue is really old, will close. If you feel that the issue is still present in the latest version, don't hesitate to reopen.

**Closed by davidovich** 2017-02-17 21:08 UTC

**Comment by MinchinWeb** [comment] 2017-02-18 17:31
Thanks for all your work on this! I can confirm that they installed for me on Windows without issues. I'll have to read up on them and work to add them into my workflow.
