### ISSUE TITLE
Differing results based on platform pip-compile is run from

### ISSUE THREAD

**Issue by ssbarnea** [jazzband/pip-tools#1220] opened 2020-11-12 08:45 UTC
While I do understand that different platforms may produce different results it i also impossible to run pip-compile for a specific target platform.

Even if you product officially ships on a single platform, the developers may use a plethora of variations when they propose a change, they should be able to recompile the target requirements.txt file.

For example if their dev machine is MacOS, or even a different python version that the shipped one you do end-up with a different requirements.txt file (even if sometimes only comments differ).

This does not play well at all with CI usage, where you likely have one job that recompiles requirements.in and fails the build if the produced file is different.

We clearly need a reproducible way to recompile requirements that does not force PR creator to execute pip-compile on a very particular platform.

**Comment by stianlagstad** [comment] 2023-09-13 10:45
Here's an issue describing the same problem with another package manager: https://github.com/pypa/pipenv/issues/5130

**Comment by webknjaz** [comment] 2023-09-13 12:15
FWIW this is explained in README already.

**Comment by doronbehar** [comment] 2024-08-02 09:17
BTW I tried today to use the `--pip-args '--platform=linux-armv7l'` for [this `pyproject.toml`](https://github.com/linien-org/linien/blob/1527649fa4aa4d92ea28c323f13fbf1c26f023d4/linien-server/pyproject.toml#L30), and the resulting `requirements.txt` file didn't include the `pyrp3` dependency... I wonder why 🤔.

> FWIW this is explained in README already.

What is explained?

**Comment by webknjaz** [comment] 2024-12-04 14:33
Closing as duplicate of #826. No need to have multiple competing discussions of the same thing.

**Closed by webknjaz** 2024-12-04 14:33 UTC
Labels: feature
