### ISSUE TITLE
pip-compile suffix numpy with +mkl

### ISSUE THREAD

**Issue by ingolfured** [jazzband/pip-tools#1471] opened 2021-08-23 10:27 UTC
I currently have a setup.cfg with `numpy==1.19.5` as dependency. When I rebuild a requirements.txt using `pip-compile` on Windows 10, it adds a line `numpy==1.19.5+mkl` which later on can't be found by my Linux Jenkins instance. How can I tell `pip-compile` to stop adding `+mkl` as a suffix to the version?

Thanks
Ingo

#### Environment Versions

1. Windows 10 (when run pip-compile) but Linux (when run pip-sync)
1. Python version: Python 3.6
1. pip version: 21.2.2 
1. pip-tools version: 6.2.0

#### Steps to replicate

1. Have a setup.cfg with a 
```
[options]
install_requires =
    numpy==1.19.5
```
2. run `pip-compile`
3. Have a look at your `requirements.txt` for a line `numpy==1.19.5+mkl` `

#### Expected result
It should be `numpy==1.19.5`

#### Actual result
 `numpy==1.19.5+mkl`

**Comment by 1oglop1** [comment] 2021-08-24 06:13
I'd say you do not want to run `pip-compile` on your windows machine. Just make `pip-compile` as part of your CI job instead

**Comment by AndydeCleyre** [comment] 2021-09-21 20:44
@ingolfured 

It's been about a month, and AFAICT this is working as intended, so I'm closing the issue, but please write back if there's more to add here. Thanks!

**Closed by AndydeCleyre** 2021-09-21 20:44 UTC
