### ISSUE TITLE
pip-sync fails, printing help text of `pip uninstall`

### ISSUE THREAD

**Issue by antonagestam** [jazzband/pip-tools#1332] opened 2021-02-26 09:37 UTC
Invoking `pip-sync` started acting super weird and just printing the help text of `pip uninstall` in my virtualenv. Tried deactivating/activating the virtualenv without success. After recreating the virtualenv it functions normally 🤔

#### Environment Versions

1. OS Type: MacOS Big Sur
1. Python version: 3.9.0
1. pip version: 20.3.3, 21.0.1 (tried both)
1. pip-tools version: 5.5.0

#### Steps to replicate

1. `$ pip-sync reqs/requirements.txt reqs/dev-requirements.txt`

(same result with `$ pip-sync reqs/requirements.txt`)

#### Expected result

...

#### Actual result

```
Usage:   
  /Users/__redacted__/.pyenv/versions/3.9.0/envs/__redacted__/bin/python3.9 -m pip uninstall [options] <package> ...
  /Users/__redacted__/.pyenv/versions/3.9.0/envs/__redacted__/bin/python3.9 -m pip uninstall [options] -r <requirements file> ...

Description:
  Uninstall packages.
  
  pip is able to uninstall most installed packages. Known exceptions are:
  
  - Pure distutils packages installed with ``python setup.py install``, which
    leave behind no metadata to determine what files were installed.
  - Script wrappers installed by ``python setup.py develop``.

Uninstall Options:
  -r, --requirement <file>    Uninstall all the packages listed in the given requirements file.  This option can be used multiple times.
  -y, --yes                   Don't ask for confirmation of uninstall deletions.

General Options:
  -h, --help                  Show help.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to WARNING, ERROR, and CRITICAL logging
                              levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to alternate CA bundle.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be removed in the future.
```

**Comment by atugushev** [comment] 2021-02-28 15:51
Hello @antonagestam,

Thanks for the report. It looks like `pip-tools` tries to uninstall an empty list of packages, which is weird because there is a [check](https://github.com/jazzband/pip-tools/blob/f54ad96932f2cf32cc039848881555215e50cccd/piptools/sync.py#L216) for an empty list. Could you please provide the following additional info:

1. Contents of files `reqs/requirements.txt` and `reqs/dev-requirements.txt files` (if possible)
2. Output of `python -m pip list`
3. Output of `python -m piptools sync -a`
4. Output of `python -m piptools sync -v`

**Comment by AndydeCleyre** [comment] 2021-04-07 13:54
Hello @antonagestam, we don't yet have enough info to reproduce (especially the contents of `reqs/requirements.txt`).

Please do follow up so we can tackle this issue.

As it's been over a month since we've heard from you, I'm inclined to close this issue if we get to the end of April without any more information, but you can always come back later and we'll re-open if you can still reproduce the problem.

Thanks for the report, and any more info!

**Comment by antonagestam** [comment] 2021-04-07 14:10
@AndydeCleyre @atugushev Feel free to close this. I don't know how to reproduce this myself, as I mentioned I recreated the virtualenv and haven't had the issue since. This happened for a commercial project and I am not at liberty to disclose our dependencies.

**Comment by AndydeCleyre** [comment] 2021-04-07 14:19
Thanks @antonagestam!

Just let us know if it pops up again.

**Closed by AndydeCleyre** 2021-04-07 14:19 UTC
Labels: bug, needs more info, needs reproduce
