### ISSUE TITLE
pip options in compiled requirement are ignored by pip-sync

### ISSUE THREAD

**Issue by yakky** [jazzband/pip-tools#367] opened 2016-05-28 18:56 UTC
pip-sync ignores pip options declared in requirements file
##### Steps to replicate
1. pip-compile a requirements file with `--extra-index-url http://my.devpi`
2. run pip-sync 
##### Expected result

Packages hosted in http://my.devpi gets installed
##### Actual result

pip-sync exit with error because it can't find packages from `http://my.devpi`

**Comment by estan** [comment] 2017-01-05 12:58
I think this is a duplicate of #192 , right @nvie ? Also there's #321 which is more of a general wish for passing options through to `pip`.

**Comment by davidovich** [comment] 2017-02-19 16:28
Closing as implemented by #283. Reopen if you feel that recent pip-tools does not support this.

**Closed by davidovich** 2017-02-19 16:28 UTC

**Comment by arthurio** [comment] 2017-03-09 01:00
@davidovich I'm using [1.8.1rc3](https://github.com/jazzband/pip-tools/releases/tag/1.8.1rc3) and have the same behavior:
1. Run `pip-compile requirements.in` (has `--extra-index-url http://my.devpi`):

**Result (as expected)**
Puts the `--extra-index-url http://my.devpi` at the top of the generated `requirements.txt` file and list all the dependencies with versions.

2. Run `pip-sync requirements.txt`:

**Expected result**
Package hosted in http://mydevpi gets installed

**Actual result**
`Could not find a version that satisfies the requirement mymodule==0.1.0`
(where `mymodule` is the package hosted in http://mydevpi)

**Comment by nefarioustim** [comment] 2017-08-27 18:08
I am seeing the same behaviour as @arthurio in 1.9.0. My `--extra-index-url` is declared inside the `requirements.txt` and is being ignored when I run `pip-sync`.

I do not think this bug is truly closed.

**Comment by nefarioustim** [comment] 2017-08-27 18:13
Just as a follow up, I can confirm that if I pass `--extra-index-url` as a parameter to the call to `pip-sync` it works as expected. It is only when `--extra-index-url` is included _within_ the `requirements.txt` that it is overlooked.
