### ISSUE TITLE
Feature request: Support configuration file

### ISSUE THREAD

**Issue by stphnlyd** [jazzband/pip-tools#1773] opened 2022-12-13 08:12 UTC
#### What's the problem this feature will solve?

In our workplace we would like to always enforce some options for example --no-emit-index-url. 

#### Describe the solution you'd like

pip-tools to support a rc file or ini file for configuring default options. 

For example, 

```
[pip-compile]
no-emit-index-url = true
```

with above configuration file `pip-compile` will by default behave `--no-emit-index-url`. And user can override that with explicit `pip-compile --emit-index-url`

**Comment by atugushev** [comment] 2022-12-13 09:33
Closing as a duplicate of #604.

**Closed by atugushev** 2022-12-13 09:33 UTC
Labels: duplicate
