### ISSUE TITLE
Environment markers are not applied evenly

### ISSUE THREAD

**Issue by Sclafus** [jazzband/pip-tools#1754] opened 2022-12-07 13:45 UTC
#### Environment Versions

1. OS Type: **Windows 10**
1. Python version: **Python 3.10.7**
1. pip version: **pip 22.3.1**
1. pip-tools version: **pip-compile 6.11.0**

#### Steps to replicate

1. Write a `requirements.in` file with the following content
 ```python
wmi ; sys_platform=='win32'
```
2. `pip-compile`

#### Expected result
```python
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile
#
pywin32==305 ; sys_platform == "win32"
    # via wmi
wmi==1.5.1 ; sys_platform == "win32"
    # via -r requirements.in
```
Note that __both__ `pywin32` and `wmi` are installed on win32 platforms. This is the expected result since `pywin32` is installed by `wmi` and is required only by that package, which has the environment marker for win32 systems.

#### Actual result
```python
#
# This file is autogenerated by pip-compile with Python 3.10
# by the following command:
#
#    pip-compile
#
pywin32==305
    # via wmi
wmi==1.5.1 ; sys_platform == "win32"
    # via -r requirements.in
```

Is this intended? Am I missing some edge cases?

**Comment by atugushev** [comment] 2022-12-07 13:51
Duplicate of #563

**Closed** 2022-12-07 13:52 UTC
Labels: duplicate, markers
