### ISSUE TITLE
pip-sync doesn't respect `--extra-index-url` in requirements.txt

### ISSUE THREAD

**Issue by cbows** [jazzband/pip-tools#952] opened 2019-10-19 14:38 UTC
Although there is an `--extra-index-url` flag in requirements.txt pip-sync is not aware of it.

#### Environment Versions

1. MacOS 10.14.6
1. Python version: 3.7.4
1. pip version:  19.3.1
1. pip-tools version: 4.2.0

#### Steps to replicate

1. Create requirements.txt with extra-index-url

```
--extra-index-url http://localhost:8080/simple/

myspecialpackage==1.0.0
```

2. Run pip-sync

#### Expected result

It should find the package in the extra index.

#### Actual result

pip-sync fails. Error is something like:

```
subprocess.CalledProcessError: Command '['~/myapp/.venv/bin/python', '-m', 'pip', 'install', '-r', '/var/folders/.../tmpXXXXXXX']' returned non-zero exit status 1.
```

Notice: The command call array does not contain the relevant `--extra-index-url` flag.

#### Current workaround

Maybe this is not a bug, but intended behaviour. Currently I just specify the extra-index-url like `pip-sync --extra-index-url http://localhost:8080/simple/` and it works. Also `pip install -r requirements.txt` works as well.

Would it make sense to include extra index urls from the requirements files? I guess this would also apply for other options like `trusted-host` etc...

**Comment by atugushev** [comment] 2019-10-19 15:20
Hello @cbows,

Thanks for the issue! It's a duplicate of #638.

**Comment by atugushev** [comment] 2019-10-19 19:37
@cbows 

I've prepared a pull request (#824), which adds support of `--extra-index-url` and the other options. Any feedback, review/test would be appreciated!

**Comment by atugushev** [comment] 2019-10-19 19:42
I'll close this in favor of #638.

**Closed by atugushev** 2019-10-19 19:42 UTC
Labels: duplicate
